import { NextResponse } from 'next/server';
const PAIRS:Record<string,string>={BTC:'PF_XBTUSD',ETH:'PF_ETHUSD',SOL:'PF_SOLUSD',HYPE:'PF_HYPEUSD'};
const START=Date.parse('2026-03-13T00:00:00Z'), END=Date.parse('2026-09-13T00:00:00Z');
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){if(c.length<2)return 0;const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(r)}
function piv(c:C[],dir:'LONG'|'SHORT',w:number){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,vals=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...vals):v===Math.max(...vals))r.push({index:i,price:v})}return r}
function tl(c:C[],dir:'LONG'|'SHORT',w:number,look:number){const p=piv(c,dir,w).filter(x=>x.index>=Math.max(0,c.length-look));if(p.length<2)return null;const a=p.at(-2),b=p.at(-1),dx=b.index-a.index;if(dx<=0)return null;const slope=(b.price-a.price)/dx;if((dir==='LONG'&&slope<=0)||(dir==='SHORT'&&slope>=0))return null;const intercept=a.price-slope*a.index;for(let i=b.index+1;i<c.length;i++){const line=slope*i+intercept,buf=Math.max(line*.005,atr(c)*.35);if(dir==='LONG'&&c[i].close<line-buf)return null;if(dir==='SHORT'&&c[i].close>line+buf)return null}return{price:slope*(c.length-1)+intercept,slope,anchor:b.index}}
function dailyBias(c:C[]){const by=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!by.has(k))by.set(k,[]);by.get(k)!.push(x)}const d=[...by.values()].map(b=>b.at(-1)!.close);if(d.length<20)return null;const f=ema(d,5).at(-1)!,s=ema(d,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function rsi(a:number[],p=14){if(a.length<2)return 50;let g=0,l=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}const n=Math.min(p,a.length-1),ag=g/n,al=l/n;return al===0?100:100-100/(1+ag/al)}
function stoch(a:number[]){const rv:number[]=[];for(let i=14;i<a.length;i++)rv.push(rsi(a.slice(i-14,i+1)));if(rv.length<14)return{k:50,d:50};const raw:number[]=[];for(let i=13;i<rv.length;i++){const w=rv.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100)}const k=raw.at(-1)??50,d=avg(raw.slice(-3));return{k,d}}
function signal(c:C[],dir:'LONG'|'SHORT',w:number,look:number){const t=tl(c,dir,w,look);if(!t)return null;const price=c.at(-1)!.close,near=Math.abs(price-t.price)/t.price<.012,cl=c.map(x=>x.close),e8=ema(cl,8).at(-1)!,e21=ema(cl,21).at(-1)!,st=stoch(cl),turn=dir==='LONG'?st.k>st.d:st.k<st.d,extreme=dir==='LONG'?st.k<20:st.k>80,confirm=dir==='LONG'?price>c.at(-1)!.open:price<c.at(-1)!.open,aligned=dir==='LONG'?price>e8&&price>e21:price<e8&&price<e21;if(!(near&&(extreme||turn)))return null;const entry=price,a=atr(c),stop=dir==='LONG'?Math.max(entry-a*2,entry*.965):Math.min(entry+a*2,entry*1.035);const risk=Math.abs(entry-stop);return{dir,entry,stop,tp:dir==='LONG'?entry+risk*2:entry-risk*2,signal:extreme?'E1':'E2',tl:t.price,near,confirm,aligned}}
function run(c:C[],w:number,look:number){let tr:any=null;const out={trades:0,wins:0,losses:0,r:0,signals:0,e1:0,e2:0};for(let i=80;i<c.length;i++){const h=c.slice(0,i+1);if(tr){const x=c[i],win=tr.dir==='LONG'?x.high>=tr.tp:x.low<=tr.tp,loss=tr.dir==='LONG'?x.low<=tr.stop:x.high>=tr.stop;if(win){out.trades++;out.wins++;out.r+=2;tr=null;continue}if(loss){out.trades++;out.losses++;out.r-=1;tr=null;continue}}if(!tr){const d=dailyBias(h);if(d){const s=signal(h,d,w,look);if(s){out.signals++;s.signal==='E1'?out.e1++:out.e2++;tr=s}}}}if(tr){const x=c.at(-1)!,p=tr.dir==='LONG'?x.close-tr.entry:tr.entry-x.close,r=p/Math.abs(tr.entry-tr.stop);out.trades++;if(r>0)out.wins++;else out.losses++;out.r+=r}return out}
async function fetchPair(pair:string){const u=`https://futures.kraken.com/api/charts/v1/trade/${PAIRS[pair]}/4h?from=${Math.floor((START-45*86400000)/1000)}&to=${Math.floor(END/1000)}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${pair} ${r.status}`);const d=await r.json();return (d.candles||[]).map((x:any)=>({timestamp:Number(x.time),open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume})).filter((x:C)=>x.timestamp>=START&&x.timestamp<=END)}
export async function GET(){const configs:any={P2_60:[2,60],P3_90:[3,90],P4_120:[4,120],P5_120:[5,120]};const by:any={};for(const pair of Object.keys(PAIRS)){const c=await fetchPair(pair);by[pair]={candles:c.length};for(const [k,[w,l]] of Object.entries(configs)){by[pair][k]=run(c,w,l)}}const summary:any={};for(const k of Object.keys(configs)){const a={trades:0,wins:0,losses:0,r:0,signals:0,e1:0,e2:0};for(const p of Object.keys(by)){for(const x of ['trades','wins','losses','r','signals','e1','e2'] as const)a[x]+=by[p][k][x]}summary[k]={...a,winRate:a.trades?100*a.wins/a.trades:0,pf:a.losses?a.wins*2/a.losses:0}}return NextResponse.json({period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},note:'Research only. Point-to-point pivot TL robustness test using Kraken Futures 4H; no production strategy changes.',summary,byAsset:by})}
