import { NextResponse } from 'next/server';
const PAIRS:Record<string,string>={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'};
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(r)}
function rsi(a:number[],p=14){let g=0,l=0,n=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d;n++}if(!n)return 50;const ag=g/n,al=l/n;if(al===0)return 100;return 100-100/(1+ag/al)}
function stoch(a:number[]){const rv:number[]=[];for(let i=14;i<a.length;i++)rv.push(rsi(a.slice(i-14,i+1)));if(rv.length<14)return{k:50,d:50};const raw:number[]=[];for(let i=13;i<rv.length;i++){const w=rv.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100)}const kv:number[]=[];for(let i=2;i<raw.length;i++)kv.push(avg(raw.slice(i-2,i+1)));return kv.length<3?{k:50,d:50}:{k:kv.at(-1)!,d:avg(kv.slice(-3))}}
function pivots(c:C[],dir:'LONG'|'SHORT',w:number){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,vals=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...vals):v===Math.max(...vals))r.push({index:i,price:v})}return r}
function point(p:any[],c:C[],dir:any){if(p.length<2)return null;const a=p.at(-2),b=p.at(-1),dx=b.index-a.index;if(dx<=0)return null;const slope=(b.price-a.price)/dx;if((dir==='LONG'&&slope<=0)||(dir==='SHORT'&&slope>=0))return null;return{price:slope*(c.length-1)+(a.price-slope*a.index),slope,anchor:b.index}}
function regression(p:any[],c:C[],dir:any){if(p.length<3)return null;const n=p.length,sx=p.reduce((s,x)=>s+x.index,0),sy=p.reduce((s,x)=>s+x.price,0),sxy=p.reduce((s,x)=>s+x.index*x.price,0),sx2=p.reduce((s,x)=>s+x.index*x.index,0),den=n*sx2-sx*sx;if(!den)return null;const slope=(n*sxy-sx*sy)/den;if((dir==='LONG'&&slope<=0)||(dir==='SHORT'&&slope>=0))return null;const inter=(sy-slope*sx)/n;return{price:slope*(c.length-1)+inter,slope,anchor:p.at(-1).index}}
function structured5(p:any[],dir:any){let o:any[]=[];for(const x of p){if(!o.length){o.push(x);continue}const z=o.at(-1);if(dir==='LONG'?x.price>z.price:x.price<z.price)o.push(x)}return o.slice(-5)}
function tl(c:C[],dir:any,v:number){const w=v===5?5:2,all=pivots(c,dir,w),look=v===5?120:60,recent=all.filter(x=>x.index>=Math.max(0,c.length-look));if(recent.length<2)return null;let p=v===5?structured5(recent,dir):recent.slice(-5);if(p.length<(v===5?3:2))return null;const latest=p.at(-1).index;p=p.filter(x=>x.index>=latest-(v===5?120:72));const q=v===5?regression(p,c,dir):point(p,c,dir);if(!q)return null;const buffer=Math.max(q.price*.005,atr(c)*.35);for(let i=q.anchor+1;i<c.length;i++){const line=q.slope*i+(q.price-q.slope*(c.length-1));if(dir==='LONG'&&c[i].close<line-buffer)return null;if(dir==='SHORT'&&c[i].close>line+buffer)return null}return q}
function bias(c:C[]){const d=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!d.has(k))d.set(k,[]);d.get(k)!.push(x)}const a=[...d.values()].map(x=>x.at(-1)!.close);if(a.length<14)return null;const f=ema(a,5).at(-1)!,s=ema(a,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function signal(c:C[],dir:any,v:number){const t=tl(c,dir,v);if(!t)return null;const price=c.at(-1)!.close,near=Math.abs((price-t.price)/t.price)<.012,st=stoch(c.map(x=>x.close)),turn=dir==='LONG'?st.k>st.d:st.k<st.d,ext=dir==='LONG'?st.k<20:st.k>80;if(!near||(!ext&&!turn))return null;const a=atr(c),stop=dir==='LONG'?Math.max(price-a*2,price*.965):Math.min(price+a*2,price*1.035);return{entry:price,stop,dir}}
function run(c:C[],v:number){let tr:any=null,o={trades:0,wins:0,losses:0,net:0,gp:0,gl:0};for(let i=40;i<c.length;i++){const h=c.slice(0,i+1);if(tr){const x=c[i],r=Math.abs(tr.entry-tr.stop),win=tr.dir==='LONG'?x.high>=tr.entry+r*2:x.low<=tr.entry-r*2,sl=tr.dir==='LONG'?x.low<=tr.stop:x.high>=tr.stop;if(sl||win){const pnl=win?(tr.dir==='LONG'?r*2:-r*2):(tr.dir==='LONG'?tr.stop-tr.entry:tr.entry-tr.stop);o.trades++;if(pnl>=0){o.wins++;o.gp+=pnl}else{o.losses++;o.gl+=-pnl}o.net+=pnl;tr=null;continue}}if(!tr){const d=bias(h),s=d&&signal(h,d,v);if(s)tr=s}}if(tr){const p=c.at(-1)!.close,pnl=tr.dir==='LONG'?p-tr.entry:tr.entry-p;o.trades++;if(pnl>=0){o.wins++;o.gp+=pnl}else{o.losses++;o.gl+=-pnl}o.net+=pnl}return{...o,winRate:o.trades?100*o.wins/o.trades:0,pf:o.gl?o.gp/o.gl:0}}
async function fetchPair(pair:string){const since=Math.floor(Date.parse('2026-05-01T00:00:00Z')/1000),u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair]}&interval=240&since=${since}`,r=await fetch(u,{cache:'no-store'}),d=await r.json(),key=Object.keys(d.result||{}).find(k=>k!=='last');return(d.result?.[key]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:C)=>x.timestamp<=Date.parse('2026-09-10T00:00:00Z'))}
export async function GET(){const out:any={method:'3 rolling folds, 42d train -> 21d OOS; pick V4/V5 on train net, freeze pick',assets:{}};for(const pair of Object.keys(PAIRS)){const c=await fetchPair(pair),folds:any[]=[];for(let end=63;end<=c.length;end+=21){const train=c.slice(end-63,end-21),test=c.slice(end-21,end),v4=run(train,4),v5=run(train,5),pick=v4.trades<2&&v5.trades>=2?5:v5.trades<2&&v4.trades>=2?4:(v4.net>=v5.net?4:5),o4=run(test,4),o5=run(test,5);folds.push({train:[train[0]?.timestamp,train.at(-1)?.timestamp],test:[test[0]?.timestamp,test.at(-1)?.timestamp],trainV4:v4,trainV5:v5,picked:`V${pick}`,oosPicked:pick===4?o4:o5,oosV4:o4,oosV5:o5})}out.assets[pair]={candles:c.length,folds}}return NextResponse.json(out)}