import {NextResponse} from 'next/server';
const P:any={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'};type C={t:number;o:number;h:number;l:number;c:number;v:number};
const avg=(a:number[])=>a.reduce((x,y)=>x+y,0)/(a.length||1);function atr(c:C[]){return avg(c.slice(-14).map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-c[c.length-15+i].c),Math.abs(x.l-c[c.length-15+i].c)):x.h-x.l))}
function ema(a:number[],p:number){const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function piv(c:C[],d:string){let r:any[]=[];for(let i=2;i<c.length-2;i++){const z=d==='L'?c[i].l:c[i].h,w=c.slice(i-2,i+3).map(x=>d==='L'?x.l:x.h);if(z===(d==='L'?Math.min(...w):Math.max(...w)))r.push({i,p:z})}return r}
function line(a:any,b:any,c:C[],d:string){let s=(b.p-a.p)/(b.i-a.i);if(d==='L'?s<=0:s>=0)return null;let q={s,p:s*(c.length-1)+a.p-s*a.i,a,b};let buf=Math.max(q.p*.005,atr(c)*.35);for(let i=b.i+1;i<c.length;i++){let y=s*i+a.p-s*a.i;if(d==='L'?c[i].c<y-buf:c[i].c>y+buf)return null}return q}
function tl(c:C[],d:string,v:number){let p=piv(c,d);if(p.length<2)return null;if(v===1)return line(p.at(-2),p.at(-1),c,d);if(v===2){let q:any[]=[];for(let x of p)if(!q.length||(d==='L'?x.p>q.at(-1).p:x.p<q.at(-1).p))q.push(x);return q.length>1?line(q.at(-2),q.at(-1),c,d):null}let best:any=null;for(let i=0;i<p.length-1;i++)for(let j=i+1;j<p.length;j++){let q=line(p[i],p[j],c,d);if(!q)continue;if(v===3?(!best||j-i>best.span):v===4?(!best||Math.abs(q.s)<Math.abs(best.s)):true){best={...q,span:j-i,touch:0};for(let k=i;k<p.length;k++){let y=q.s*p[k].i+p[i].p-q.s*p[i].i;if(Math.abs(p[k].p-y)<=Math.max(q.p*.012,atr(c)*.7))best.touch++}}}if(v===5){best=null;for(let i=0;i<p.length-1;i++)for(let j=i+1;j<p.length;j++){let q=line(p[i],p[j],c,d);if(!q)continue;let touch=0;for(let k=i;k<p.length;k++){let y=q.s*p[k].i+p[i].p-q.s*p[i].i;if(Math.abs(p[k].p-y)<=Math.max(q.p*.012,atr(c)*.7))touch++}if(!best||touch>best.touch||(touch===best.touch&&j-i>best.span))best={...q,touch,span:j-i}}}return best}
function run(c:C[],v:number){let tr:any=null,o:any={trades:0,wins:0,losses:0,net:0,gp:0,gl:0};for(let i=60;i<c.length;i++){let h=c.slice(0,i+1);if(tr){let x=c[i],r=Math.abs(tr.e-tr.s),win=tr.d==='L'?x.h>=tr.e+2*r:x.l<=tr.e-2*r,sl=tr.d==='L'?x.l<=tr.s:x.h>=tr.s;if(win||sl){let n=win?(tr.d==='L'?2*r:-2*r):(tr.d==='L'?tr.s-tr.e:tr.e-tr.s);o.trades++;if(n>=0)o.wins++,o.gp+=n;else o.losses++,o.gl-=n;o.net+=n;tr=null;continue}}let daily=new Map<string,number>();for(let x of h){let k=new Date(x.t).toISOString().slice(0,10);daily.set(k,x.c)}let a=[...daily.values()];let d=a.length>13?(ema(a,5).at(-1)!>ema(a,13).at(-1!)?'L':'S'):null;if(!tr&&d){let q=tl(h,d,v);if(q){let pr=h.at(-1)!.c,st=d==='L'?pr<q.p*.012+q.p&&pr>q.p*.988:pr<q.p*1.012&&pr>q.p*.988;if(st)tr={e:pr,s:d==='L'?Math.max(pr-2*atr(h),pr*.965):Math.min(pr+2*atr(h),pr*1.035),d}}}}if(tr){let pr=c.at(-1)!.c,n=tr.d==='L'?pr-tr.e:tr.e-pr;o.trades++;if(n>=0)o.wins++,o.gp+=n;else o.losses++,o.gl-=n;o.net+=n}return{...o,winRate:o.trades?100*o.wins/o.trades:0,pf:o.gl?o.gp/o.gl:0}}
async function get(k:string){let u=`https://api.kraken.com/0/public/OHLC?pair=${P[k]}&interval=240&since=${Math.floor(Date.parse('2026-03-01')/1000)}`,d=await(await fetch(u,{cache:'no-store'})).json(),key=Object.keys(d.result||{}).find(x=>x!=='last');return(d.result?.[key]||[]).map((x:any)=>({t:x[0]*1000,o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[6]})).filter((x:C)=>x.t<=Date.parse('2026-09-13'))}
export async function GET(){let out:any={period:'2026-03-01 to 2026-09-13',assets:{}};for(let k of Object.keys(P)){let c=await get(k),r:any={};for(let v=1;v<=5;v++)r['V'+v]=run(c,v);out.assets[k]={candles:c.length,results:r}}return NextResponse.json(out)}