import { NextResponse } from 'next/server';

const PAIRS: Record<string,string>={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'};
const START=Date.parse('2026-07-31T00:00:00Z');
const END=Date.parse('2026-09-10T00:00:00Z');
const TL_THRESHOLD=.012;
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
type T={entry:number;stop:number;tp1:number;tp2:number;tp3:number;dir:'LONG'|'SHORT';openTs:number;stage:number;r1:boolean;r15:boolean;r2:boolean};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const median=(a:number[])=>{if(!a.length)return 0;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){if(c.length<2)return 0;const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(r)}
function rsi(a:number[],p=14){if(a.length<2)return 50;let g=0,l=0,n=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l+=-d;n++}if(!n)return 50;const ag=g/n,al=l/n;if(al===0)return 100;return 100-100/(1+ag/al)}
function wilder(a:number[],p:number){if(!a.length)return[];const seed=a.slice(0,p);if(seed.length<p)return[];const r=[avg(seed)];for(let i=p;i<a.length;i++)r.push((r.at(-1)!*(p-1)+a[i])/p);return r}
function dmi(c:C[],p=14){if(c.length<p+2)return{adx:0,plus:0,minus:0};const tr:number[]=[],pl:number[]=[],mi:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));const up=x.high-q.high,down=q.low-x.low;pl.push(up>down&&up>0?up:0);mi.push(down>up&&down>0?down:0)}const t=wilder(tr,p),pd=wilder(pl,p),md=wilder(mi,p),dx:number[]=[],plus:number[]=[],minus:number[]=[];for(let i=0;i<t.length;i++){plus.push(t[i]?pd[i]/t[i]*100:0);minus.push(t[i]?md[i]/t[i]*100:0);const s=plus[i]+minus[i];dx.push(s?Math.abs(plus[i]-minus[i])/s*100:0)}const ad=wilder(dx,p);return{adx:ad.at(-1)||0,plus:plus.at(-1)||0,minus:minus.at(-1)||0}}
function daily(c:C[]){const m=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!m.has(k))m.set(k,[]);m.get(k)!.push(x)}return [...m.values()].map(b=>({timestamp:b[0].timestamp,open:b[0].open,high:Math.max(...b.map(x=>x.high)),low:Math.min(...b.map(x=>x.low)),close:b.at(-1)!.close,volume:b.reduce((s,x)=>s+x.volume,0)}))}
function pivots(c:C[],dir:'LONG'|'SHORT',w:number){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,vals=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...vals):v===Math.max(...vals))r.push({index:i,price:v})}return r}
function point(p:any[],c:C[],dir:'LONG'|'SHORT'){if(p.length<2)return null;const a=p.at(-2),b=p.at(-1),dx=b.index-a.index;if(dx<=0)return null;const slope=(b.price-a.price)/dx;if(dir==='LONG'&&slope<=0||dir==='SHORT'&&slope>=0)return null;return{price:slope*(c.length-1)+(a.price-slope*a.index),slope,anchor:b.index}}
function dailyTrendline(d:C[],dir:'LONG'|'SHORT'){const p=pivots(d,dir,2).slice(-5);if(p.length<2)return null;const q=point(p,d,dir);if(!q)return null;const buffer=Math.max(q.price*.005,atr(d)*.35);for(let i=q.anchor+1;i<d.length;i++){const line=q.slope*i+(q.price-q.slope*(d.length-1));if(dir==='LONG'&&d[i].close<line-buffer||dir==='SHORT'&&d[i].close>line+buffer)return{...q,valid:false};}return{...q,valid:true}}
function structure(d:C[],dir:'LONG'|'SHORT'){const hs=pivots(d,'SHORT',2),ls=pivots(d,'LONG',2);if(hs.length<2||ls.length<2)return false;return dir==='LONG'?hs.at(-1).price>hs.at(-2).price&&ls.at(-1).price>ls.at(-2).price:hs.at(-1).price<hs.at(-2).price&&ls.at(-1).price<ls.at(-2).price}
function forwardRegime(d:C[],h:C[]){if(d.length<210||h.length<30)return{state:'TRANSITION',score:0,detail:{}};const cl=d.map(x=>x.close),e20=ema(cl,20),e50=ema(cl,50),e200=ema(cl,200),last=cl.at(-1)!,slope20=e20.at(-1)!-e20.at(-4)!;let score=0;const bullStruct=structure(d,'LONG'),bearStruct=structure(d,'SHORT');if(bullStruct)score+=2;if(bearStruct)score-=2;const tlL=dailyTrendline(d,'LONG'),tlS=dailyTrendline(d,'SHORT');if(tlL){if(last>=tlL.price)score+=2;else score-=2}if(tlS){if(last<=tlS.price)score-=2;else score+=2}if(last>e20.at(-1)!&&e20.at(-1)!>e50.at(-1)!&&e50.at(-1)!>e200.at(-1)!&&slope20>0)score+=2;else if(last<e20.at(-1)!&&e20.at(-1)!<e50.at(-1)!&&e50.at(-1)!<e200.at(-1)!&&slope20<0)score-=2;else if(last>e20.at(-1)!&&slope20>0)score+=1;else if(last<e20.at(-1)!&&slope20<0)score-=1;const rv=rsi(cl,14),rvPrev=rsi(cl.slice(0,-3),14);if(rv>50&&rv>=rvPrev)score+=1;else if(rv<50&&rv<=rvPrev)score-=1;const dm=dmi(d);if(dm.adx>=20){if(dm.plus>dm.minus)score+=1;else if(dm.minus>dm.plus)score-=1}const hcl=h.map(x=>x.close),h5=ema(hcl,5).at(-1)!,h13=ema(hcl,13).at(-1)!,h8=ema(hcl,8).at(-1)!,h21=ema(hcl,21).at(-1)!;if(h5>h13)score+=1;else if(h5<h13)score-=1;if(h8>h21)score+=1;else if(h8<h21)score-=1;const state=score>=7?'LONG ESTABLISHED':score>=4?'LONG DEVELOPING':score<=-7?'SHORT ESTABLISHED':score<=-4?'SHORT DEVELOPING':'TRANSITION';return{state,score,detail:{bullStruct,bearStruct,tlL:tlL?.price??null,tlS:tlS?.price??null,e20:e20.at(-1),e50:e50.at(-1),e200:e200.at(-1),rsi:rv,adx:dm.adx,plusDI:dm.plus,minusDI:dm.minus,h5,h13,h8,h21}}}
function h4Trendline(h:C[],dir:'LONG'|'SHORT'){const p=pivots(h,dir,2).slice(-5);return point(p,h,dir)}
function sig(h:C[],d:C[],dir:'LONG'|'SHORT'){const tl=h4Trendline(h,dir);if(!tl)return null;const p=h.at(-1)!.close,near=Math.abs((p-tl.price)/tl.price)<TL_THRESHOLD,beyond=dir==='LONG'?p>tl.price*1.008:p<tl.price*.992,cl=h.map(x=>x.close),e8=ema(cl,8).at(-1)!,e21=ema(cl,21).at(-1)!,aligned=dir==='LONG'?p>e8&&p>e21:p<e8&&p<e21,rv=rsi(cl,14),rvPrev=rsi(cl.slice(0,-2),14),turn=dir==='LONG'?rv>rvPrev:rv<rvPrev,ext=dir==='LONG'?rv<35:rv>65,confirm=dir==='LONG'?p>h.at(-1)!.open:p<h.at(-1)!.open,vol=h.at(-1)!.volume>avg(h.slice(-10).map(x=>x.volume))*1.3,dm=dmi(h),raw=near&&ext?'ENTRY_1':near&&turn&&!ext?'ENTRY_2':beyond&&confirm&&aligned&&(vol||turn||dm.adx>20)?'ADD':null;if(!raw)return null;const a=atr(h),entry=p,lo=Math.min(...h.slice(-10).map(x=>x.low)),hi=Math.max(...h.slice(-10).map(x=>x.high)),structural=dir==='LONG'?Math.min(lo,entry-a*(raw==='ADD'?1.25:2)):Math.max(hi,entry+a*(raw==='ADD'?1.25:2));const stop=dir==='LONG'?Math.max(Math.min(structural,entry*.992),entry*.965):Math.min(Math.max(structural,entry*1.008),entry*1.035),risk=Math.abs(entry-stop);return risk?{dir,entry,stop,tp1:dir==='LONG'?entry+risk:entry-risk,tp2:dir==='LONG'?entry+1.5*risk:entry-1.5*risk,tp3:dir==='LONG'?entry+2*risk:entry-2*risk,raw,risk}:null}
async function get(pair:string,interval:number,since:number){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair]}&interval=${interval}&since=${Math.floor(since/1000)}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${pair} ${interval} HTTP ${r.status}`);const j=await r.json();const k=Object.keys(j.result||{}).find(x=>x!=='last');return (j.result?.[k]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:C)=>x.timestamp<=END)}
function run(h:C[],dAll:C[]){let t:T|null=null;const o:any={trades:0,wins:0,losses:0,netR:0,r1:0,r15:0,r2:0,dur:[],slBeforeR1:0,byDir:{LONG:0,SHORT:0},byState:{},signals:0};for(let i=50;i<h.length;i++){const x=h[i],dayKey=new Date(x.timestamp).toISOString().slice(0,10),d=dAll.filter(z=>new Date(z.timestamp).toISOString().slice(0,10)<dayKey);if(!d.length||x.timestamp<START)continue;const regime=forwardRegime(d,h.slice(0,i+1));if(t){const sign=t.dir==='LONG'?1:-1,hitSL=sign>0?x.low<=t.stop:x.high>=t.stop;if(hitSL){o.trades++;if(t.stage===0){o.losses++;o.netR-=1;o.slBeforeR1++}else if(t.stage===1){o.wins++}else{o.wins++;o.netR+=.2}o.dur.push((x.timestamp-t.openTs)/3600000);t=null}else{const hitR1=!t.r1&&(sign>0?x.high>=t.tp1:x.low<=t.tp1),hitR15=!t.r15&&(sign>0?x.high>=t.tp2:x.low<=t.tp2),hitR2=!t.r2&&(sign>0?x.high>=t.tp3:x.low<=t.tp3);if(hitR1){t.r1=true;t.stage=1;o.r1++;t.stop=t.entry}if(hitR15){t.r15=true;t.stage=2;o.r15++;o.netR+=.6;t.stop=t.dir==='LONG'?t.entry+t.risk:t.entry-t.risk}if(hitR2){t.r2=true;o.r2++;o.trades++;o.wins++;o.netR+=.4;o.dur.push((x.timestamp-t.openTs)/3600000);t=null}}}if(!t&&d.length>=210){let dir:('LONG'|'SHORT')|null=null;if(regime.state.includes('LONG'))dir='LONG';else if(regime.state.includes('SHORT'))dir='SHORT';if(dir){const s=sig(h.slice(0,i+1),d,dir);if(s){t={...s,openTs:x.timestamp,stage:0,r1:false,r15:false,r2:false};o.signals++;o.byDir[dir]++;o.byState[regime.state]=(o.byState[regime.state]||0)+1}}}}if(t){const x=h.at(-1)!,sign=t.dir==='LONG'?1:-1,p=(x.close-t.entry)*sign/t.risk;o.trades++;if(p>=0)o.wins++;else o.losses++;o.netR+=p;o.dur.push((x.timestamp-t.openTs)/3600000)}return o}
export async function GET(){const byPair:any={},summary:any={trades:0,wins:0,losses:0,netR:0,r1:0,r15:0,r2:0,slBeforeR1:0,dur:[],signals:0,byDir:{LONG:0,SHORT:0},byState:{}};for(const pair of Object.keys(PAIRS)){const h=await get(pair,240,START-120*86400000),d=await get(pair,1440,START-320*86400000),r=run(h,d);byPair[pair]={fourHCandles:h.length,dailyCandles:d.length,...r};for(const k of ['trades','wins','losses','netR','r1','r15','r2','slBeforeR1','signals'])summary[k]+=r[k];summary.dur.push(...r.dur);summary.byDir.LONG+=r.byDir.LONG;summary.byDir.SHORT+=r.byDir.SHORT;for(const [k,v] of Object.entries(r.byState))summary.byState[k]=(summary.byState[k]||0)+(v as number)}return NextResponse.json({period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},model:'V28.2 Forward Regime candidate — direction selector uses daily structure + daily point-to-point TL + EMA20/50/200 regime + RSI14 + ADX/DMI + 4H 5/13 + 4H 8/21; V28 execution keeps the existing 4H point-to-point trendline, entry, SL and TP framework.',summary:{trades:summary.trades,wins:summary.wins,losses:summary.losses,winRate:+(100*summary.wins/(summary.trades||1)).toFixed(2),netR:+summary.netR.toFixed(3),avgR:+(summary.netR/(summary.trades||1)).toFixed(3),avgDurationHours:+avg(summary.dur).toFixed(2),medianDurationHours:+median(summary.dur).toFixed(2),slBeforeR1Pct:+(100*summary.slBeforeR1/(summary.losses||1)).toFixed(2),r1Rate:+(100*summary.r1/(summary.trades||1)).toFixed(2),r15Rate:+(100*summary.r15/(summary.trades||1)).toFixed(2),r2Rate:+(100*summary.r2/(summary.trades||1)).toFixed(2),signals:summary.signals,byDir:summary.byDir,byState:summary.byState},byPair})}
