import { NextResponse } from 'next/server';

const PAIRS:Record<string,string>={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'};
const START=Date.parse('2026-07-31T00:00:00Z'),END=Date.parse('2026-09-10T00:00:00Z');
const TL_THRESHOLD=.012,ARM_MAX_BARS=8;
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(r)}
function pivots(c:C[],dir:'LONG'|'SHORT',w=2){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,vals=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...vals):v===Math.max(...vals))r.push({index:i,price:v})}return r}
function point(p:any[],c:C[],dir:'LONG'|'SHORT'){if(p.length<2)return null;const a=p.at(-2),b=p.at(-1),dx=b.index-a.index;if(dx<=0)return null;const slope=(b.price-a.price)/dx;if((dir==='LONG'&&slope<=0)||(dir==='SHORT'&&slope>=0))return null;return{price:slope*(c.length-1)+(a.price-slope*a.index),slope,anchor:b.index}}
function tl(c:C[],dir:'LONG'|'SHORT'){const all=pivots(c,dir,2),recent=all.filter(x=>x.index>=Math.max(0,c.length-60));if(recent.length<2)return null;const p=recent.slice(-5),latest=p.at(-1).index,q=p.filter(x=>x.index>=latest-72);const t=point(q,c,dir);if(!t)return null;const buffer=Math.max(t.price*.005,atr(c)*.35);for(let i=t.anchor+1;i<c.length;i++){const line=t.slope*i+(t.price-t.slope*(c.length-1));if(dir==='LONG'&&c[i].close<line-buffer)return null;if(dir==='SHORT'&&c[i].close>line+buffer)return null}return t}
function dailyBias(c:C[]){const m=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!m.has(k))m.set(k,[]);m.get(k)!.push(x)}const d=[...m.values()].map(b=>b.at(-1)!.close);if(d.length<20)return null;const f=ema(d,5).at(-1)!,s=ema(d,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function stoch(c:C[]){const cl=c.map(x=>x.close);if(cl.length<32)return{k:50,d:50};const rsi=(a:number[])=>{let g=0,l=0,n=0;for(let i=1;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d;n++}if(!n||l===0)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)};const rv:number[]=[];for(let i=14;i<cl.length;i++)rv.push(rsi(cl.slice(i-14,i+1)));const raw:number[]=[];for(let i=13;i<rv.length;i++){const w=rv.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100)}const k:number[]=[];for(let i=2;i<raw.length;i++)k.push(avg(raw.slice(i-2,i+1)));return{k:k.at(-1)??50,d:avg(k.slice(-3))}}
function metrics(c:C[]){const cl=c.map(x=>x.close),f=ema(cl,5),s=ema(cl,13),n=f.length-1;return{fast:f.at(-1)!,slow:s.at(-1)!,prevFast:f[n-1]??f.at(-1)!,prevSlow:s[n-1]??s.at(-1)!,st:stoch(c)}}
function directionChange(c:C[],dir:'LONG'|'SHORT',mode:number){const m=metrics(c);const cross=dir==='LONG'?m.prevFast<=m.prevSlow&&m.fast>m.slow:m.prevFast>=m.prevSlow&&m.fast<m.slow;const candle=dir==='LONG'?c.at(-1)!.close>c.at(-1)!.open:c.at(-1)!.close<c.at(-1)!.open;const turn=dir==='LONG'?m.st.k>m.st.d:m.st.k<m.st.d;const extreme=dir==='LONG'?m.st.k<20:m.st.k>80;if(mode===1)return cross;if(mode===2)return cross||(candle&&turn);return cross||(turn&&!extreme)}
function signal(c:C[],dir:'LONG'|'SHORT',mode:number){if(!directionChange(c,dir,mode))return null;const price=c.at(-1)!.close,riskBase=dir==='LONG'?Math.min(...c.slice(-10).map(x=>x.low)):Math.max(...c.slice(-10).map(x=>x.high));const stop=dir==='LONG'?Math.max(Math.min(riskBase,price*.992),price*.965):Math.min(Math.max(riskBase,price*1.008),price*1.035);const risk=Math.abs(price-stop);if(!risk)return null;return{dir,entry:price,stop,tp1:dir==='LONG'?price+risk:price-risk,tp3:dir==='LONG'?price+risk*2:price-risk*2}}
function run(c:C[],mode:number){let arm:any=null,tr:any=null;const out:any={trades:0,wins:0,losses:0,net:0,gp:0,gl:0,armed:0,entries:0,expired:0,durations:[] as number[],captures:[] as any[]};for(let i=40;i<c.length;i++){const hist=c.slice(0,i+1),x=c[i];if(tr){const r2=tr.dir==='LONG'?x.high>=tr.tp3:x.low<=tr.tp3,sl=tr.dir==='LONG'?x.low<=tr.stop:x.high>=tr.stop;if(sl){const pnl=tr.dir==='LONG'?tr.stop-tr.entry:tr.entry-tr.stop;out.trades++;out.losses++;out.net+=pnl;out.gl+=-pnl;out.durations.push((x.timestamp-tr.ts)/3600000);tr=null;continue}if(r2){const pnl=tr.dir==='LONG'?tr.tp3-tr.entry:tr.entry-tr.tp3;out.trades++;out.wins++;out.net+=pnl;out.gp+=pnl;out.durations.push((x.timestamp-tr.ts)/3600000);tr=null;continue}continue}const db=dailyBias(hist);if(!arm&&db){const t=tl(hist,db);if(t&&Math.abs((x.close-t.price)/t.price)<TL_THRESHOLD){arm={dir:db,bar:i,tl:t.price};out.armed++}}if(arm){const age=i-arm.bar;if(age>ARM_MAX_BARS){out.expired++;arm=null}else{const s=signal(hist,arm.dir,mode);if(s){out.entries++;out.captures.push({ts:new Date(x.timestamp).toISOString(),dir:arm.dir,entry:x.close,tl:arm.tl,age});tr={...s,ts:x.timestamp};arm=null}}}}if(tr){const last=c.at(-1)!,pnl=tr.dir==='LONG'?last.close-tr.entry:tr.entry-last.close;out.trades++;if(pnl>=0){out.wins++;out.gp+=pnl}else{out.losses++;out.gl+=-pnl}out.net+=pnl;out.durations.push((last.timestamp-tr.ts)/3600000)}return out}
async function fetchPair(pair:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair]}&interval=240&since=${Math.floor(START/1000)-30*86400}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`${pair} HTTP ${r.status}`);const d=await r.json(),key=Object.keys(d.result||{}).find(k=>k!=='last');return(d.result?.[key]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:C)=>x.timestamp>=START&&x.timestamp<=END)}
export async function GET(){const byPair:any={},summary:any={};for(const p of Object.keys(PAIRS)){const c=await fetchPair(p);byPair[p]={candles:c.length,variants:{}};for(const m of [1,2,3])byPair[p].variants[m]=run(c,m)}for(const m of [1,2,3]){const a:any={trades:0,wins:0,losses:0,net:0,gp:0,gl:0,armed:0,entries:0,expired:0,durations:[]};for(const p of Object.keys(byPair)){const x=byPair[p].variants[m];for(const k of ['trades','wins','losses','net','gp','gl','armed','entries','expired'])a[k]+=x[k];a.durations.push(...x.durations)}summary[m]={trades:a.trades,wins:a.wins,losses:a.losses,winRate:a.trades?100*a.wins/a.trades:0,net:a.net,profitFactor:a.gl?a.gp/a.gl:0,avgTrade:a.trades?a.net/a.trades:0,avgDurationHours:a.durations.length?avg(a.durations):0,armed:a.armed,entries:a.entries,expired:a.expired}}return NextResponse.json({researchOnly:true,architecture:'TL anchor -> armed setup -> direction change -> Entry 1/2',armThreshold:TL_THRESHOLD,armMaxBars:ARM_MAX_BARS,period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},variants:{1:'5/13 cross only',2:'5/13 cross OR candle-direction + stochastic turn',3:'5/13 cross OR stochastic turn (non-extreme)'},summary,byPair})}
