"use client";
import {useEffect,useState} from "react";
import {Activity,Clock3,Radio,RefreshCw,ShieldCheck} from "lucide-react";

type Tone="bull"|"bear"|"neutral"|"warning";
interface Signal{ id:string;pair:string;direction:"LONG"|"SHORT";type:string;entry:number;stop:number;target:number;tp1?:number;tp2?:number;tp3?:number;rr:number;timestamp:number;expectedMove:number;context?:any;status?:string;exitReason?:string; }
interface Alert extends Signal{status:string;validity:{state:string;reason:string};currentPrice:number;slToEntryAt?:number;tp1HitAt?:number;tp2HitAt?:number;tp3HitAt?:number;}
interface Market{pair:string;price:number;trend:string;location:string;trigger:string;adx:number;rsi:number;stochK:number;stochD:number;trendlinePrice:number;distToTrendline:number|null;momentumState?:string;ema8_4h?:number;ema21_4h?:number;fourH513?:{label:string;direction:string};structureShift?:{structure:string;state:string;protectedLevel:number|null;breakDistanceAtr:number|null;reason:string};}
interface System{version?:number;lastCronRun:number;lastCronAgeMs:number|null;activePositions:number;latestAlerts?:number;historyEntries?:number;}
const PAIRS=["BTC","ETH","SOL","HYPE"];
const KRAKEN:Record<string,string>={BTC:"XBTUSD",ETH:"ETHUSD",SOL:"SOLUSD",HYPE:"HYPEUSD"};
const money=(n?:number)=>typeof n==="number"&&Number.isFinite(n)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n>=1000?0:n>=1?2:4}).format(n):"—";
const ago=(ts?:number)=>{if(!ts)return"—";const m=Math.max(0,Math.floor((Date.now()-ts)/60000));if(m<1)return"just now";if(m<60)return`${m}m`;const h=Math.floor(m/60);return h<24?`${h}h ${m%60}m`:`${Math.floor(h/24)}d`};
async function price(pair:string){try{const r=await fetch(`https://api.kraken.com/0/public/Ticker?pair=${KRAKEN[pair]}`,{cache:"no-store"});const d=await r.json();if(d.error?.length)return null;return parseFloat(d.result[Object.keys(d.result)[0]].c[0])}catch{return null}}
function tone(t:string){return t==="LONG"||t.startsWith("LONG")?"text-green-400":t==="SHORT"||t.startsWith("SHORT")?"text-red-400":"text-white/45"}
function play(m?:Market,a?:Alert){if(a?.status==="ACTIVE")return{title:`${a.direction} ACTIVE`,tone:a.direction==="LONG"?"bull":"bear" as Tone};if(m?.structureShift?.state==="SHIFT_CONFIRMED")return{title:`STRUCTURE SHIFT · ${m.structureShift.structure} → ${m.structureShift.structure==="LONG"?"SHORT":"LONG"}`,tone:"warning" as Tone};if(m?.location==="TL_INVALIDATED")return{title:"PRE-TRADE · STRUCTURE REBUILDING",tone:"warning" as Tone};if(m?.trigger==="READY")return{title:`PRE-TRADE · ${m.trend.startsWith("SHORT")?"SHORT":"LONG"} TRIGGER NEAR`,tone:m.trend.startsWith("SHORT")?"bear" as Tone:"bull" as Tone};if(m?.trend?.startsWith("SHORT"))return{title:"PRE-TRADE · SHORT SETUP",tone:"bear" as Tone};if(m?.trend?.startsWith("LONG"))return{title:"PRE-TRADE · LONG SETUP",tone:"bull" as Tone};return{title:"PRE-TRADE · WATCHING",tone:"neutral" as Tone}}
function stages(a?:Alert){return{r1:a?.tp1??a?.context?.stages?.tp1,r15:a?.tp2??a?.context?.stages?.tp2??a?.target,r2:a?.tp3??a?.context?.stages?.tp3}}
function structureRead(ss?:Market["structureShift"]){
 if(!ss)return null;
 if(ss.breakDistanceAtr===null)return{line:"Protected level —",detail:ss.reason};
 const d=ss.breakDistanceAtr;
 if(ss.state==="SHIFT_CONFIRMED")return{line:`Protected ${money(ss.protectedLevel)} · BREAK +${Math.abs(d).toFixed(2)} ATR`,detail:ss.reason};
 if(d<0)return{line:`Protected ${money(ss.protectedLevel)} · ${Math.abs(d).toFixed(2)} ATR cushion`,detail:`${ss.structure} structure intact — price is on the safe side of the protected level.`};
 return{line:`Protected ${money(ss.protectedLevel)} · ${d.toFixed(2)} ATR to break`,detail:ss.reason};
}
export default function Dashboard(){
 const[market,setMarket]=useState<Record<string,Market>>({}),[latest,setLatest]=useState<Record<string,Alert>>({}),[history,setHistory]=useState<Signal[]>([]),[logs,setLogs]=useState<string[]>([]),[prices,setPrices]=useState<Record<string,number>>({}),[system,setSystem]=useState<System|null>(null),[loading,setLoading]=useState(true),[lastFetch,setLastFetch]=useState(0),[resetting,setResetting]=useState<string|null>(null);
 async function load(){try{const r=await fetch("/api/signals",{cache:"no-store"});const d=await r.json();const m:Record<string,Market>={};for(const x of d.marketData||[])if(x?.pair)m[x.pair]=x;setMarket(m);setLatest(d.latestAlerts||{});setHistory(d.signalHistory||[]);setLogs(d.logs||[]);setSystem(d.system||null);setLastFetch(Date.now())}catch(e){console.error("CXSwitch load failed",e)}finally{setLoading(false)}}
 async function reset(pair:string){if(resetting)return;setResetting(pair);try{await fetch("/api/symbol-reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pair})});await load()}finally{setResetting(null)}}
 useEffect(()=>{load();const i=setInterval(load,30000);return()=>clearInterval(i)},[]);
 useEffect(()=>{async function lp(){const n:Record<string,number>={};await Promise.all(PAIRS.map(async p=>{const x=await price(p);if(x)n[p]=x}));setPrices(n)}lp();const i=setInterval(lp,10000);return()=>clearInterval(i)},[]);
 if(loading)return <main className="min-h-screen bg-[#070707] text-white flex items-center justify-center"><span className="text-sm text-white/35">Loading CXSwitch…</span></main>;
 return <main className="min-h-screen bg-[#070707] text-white select-text" style={{WebkitUserSelect:"text",userSelect:"text"}}>
  <nav className="border-b border-white/[0.08]"><div className="mx-auto max-w-7xl px-5 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-[#dc6b27] text-black flex items-center justify-center font-black">CX</div><div><div className="text-sm font-bold tracking-[0.18em]">CXSWITCH</div><div className="text-[9px] text-white/20 uppercase tracking-widest">V28 trading console</div></div></div><div className="flex gap-2 text-[9px]"><Badge icon={<Radio size={11}/>} text="LIVE · 10s"/><Badge icon={<Clock3 size={11}/>} text={`CRON ${system?.lastCronRun?ago(system.lastCronRun):"—"}`}/><Badge icon={<ShieldCheck size={11}/>} text="MANUAL"/></div></div></nav>
  <section className="mx-auto max-w-7xl px-5 py-6"><div className="flex justify-between items-end mb-4"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">Market board</div><h1 className="mt-1 text-lg font-semibold">V28 · current state</h1></div><div className="text-[9px] text-white/20">Updated {lastFetch?new Date(lastFetch).toLocaleTimeString():"—"}</div></div>
   <div className="grid gap-px overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.08] md:grid-cols-2 xl:grid-cols-4">{PAIRS.map(pair=>{const m=market[pair],a=latest[pair],p=prices[pair]??m?.price??a?.entry??0,s=stages(a),pl=play(m,a),ss=m?.structureShift,sr=structureRead(ss);return <article key={pair} className="bg-[#0b0b0b] p-4 min-h-[390px] flex flex-col">
    <div className="flex items-start justify-between"><div><div className="text-[9px] uppercase tracking-widest text-white/25">{pair}/USD</div><div className="mt-1 text-2xl font-semibold">{money(p)}</div></div><div className={`text-[9px] font-bold uppercase ${tone(m?.trend||"")}`}>{m?.trend||"—"}</div></div>
    <div className={`mt-3 rounded-xl border p-3 ${pl.tone==="bull"?"border-green-500/15 bg-green-500/[0.04]":pl.tone==="bear"?"border-red-500/15 bg-red-500/[0.04]":pl.tone==="warning"?"border-yellow-500/20 bg-yellow-500/[0.04]":"border-white/[0.07] bg-white/[0.02]"}`}><div className={`text-sm font-bold ${pl.tone==="bull"?"text-green-400":pl.tone==="bear"?"text-red-400":pl.tone==="warning"?"text-yellow-300":"text-white/60"}`}>{pl.title}</div></div>
    {ss&&<div className={`mt-3 rounded-xl border p-3 ${ss.state==="SHIFT_CONFIRMED"?"border-red-500/30 bg-red-500/[0.05]":ss.state==="WEAKENING"?"border-yellow-500/30 bg-yellow-500/[0.05]":"border-white/[0.07] bg-white/[0.02]"}`}><div className="text-[8px] uppercase tracking-widest text-white/20">Structure Shift · 4H test</div><div className="mt-1 text-[11px] font-bold text-white/75">{ss.structure} · {ss.state}</div><div className="mt-1 text-[9px] text-white/45">{sr?.line}</div><div className="mt-1 text-[8px] leading-4 text-white/25">{sr?.detail}</div></div>}
    <div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.015] p-3"><div className="text-[8px] uppercase tracking-widest text-white/20">Direction</div><div className="mt-1 grid grid-cols-2 gap-3"><KV l="1D 5/13" v={m?.trend?.startsWith("SHORT")?"BEARISH":m?.trend?.startsWith("LONG")?"BULLISH":"NEUTRAL"}/><KV l="4H 5/13" v={m?.fourH513?.label||"—"}/><KV l="4H 8/21" v={typeof m?.ema8_4h==="number"&&typeof m?.ema21_4h==="number"?(m.ema8_4h>=m.ema21_4h?"BULLISH":"BEARISH"):"—"}/><KV l="Location" v={m?.location||"—"}/></div></div>
    {a&&<div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="flex justify-between"><span className="text-[8px] uppercase tracking-widest text-white/25">Latest V28 · {a.type}</span><span className="text-[8px] font-bold text-green-300">{a.status}</span></div><div className={`mt-1 text-[9px] font-bold ${a.direction==="LONG"?"text-green-400":"text-red-400"}`}>{a.direction} · {ago(a.timestamp)}</div><div className="mt-2 grid grid-cols-2 gap-2"><KV l="Entry" v={money(a.entry)}/><KV l="SL" v={money(a.stop)} tone="red"/><KV l="R1" v={money(s.r1)} tone="green"/><KV l="R1.5" v={money(s.r15)} tone="green"/><KV l="R2" v={money(s.r2)} tone="green"/><KV l="R:R" v={a.rr?.toFixed(2)||"—"}/></div><div className="mt-2 text-[8px] text-white/25">40% R1 · 40% R1.5 · 20% R2</div></div>}
    {!a&&<div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3 text-[9px] text-white/30">No V28 alert currently recorded.</div>}
    <div className="mt-auto pt-3 flex justify-end"><button type="button" onClick={()=>reset(pair)} disabled={resetting===pair} className="inline-flex items-center gap-1.5 rounded-md border border-white/[0.08] px-2 py-1.5 text-[8px] uppercase tracking-wider text-white/35 hover:text-white/70 disabled:opacity-50"><RefreshCw size={10} className={resetting===pair?"animate-spin":""}/>{resetting===pair?"SYNCING":"RESET / RE-SYNC"}</button></div>
   </article>})}</div></section>

  <section className="mx-auto max-w-7xl px-5 pb-6"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] p-4"><div className="flex items-center justify-between"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">Cron / signal log</div><div className="mt-1 text-sm font-semibold">Latest system activity</div></div><div className="text-[8px] text-white/25">{logs.length} lines</div></div><pre className="mt-3 max-h-[360px] overflow-auto whitespace-pre-wrap break-words rounded-xl border border-white/[0.06] bg-black/30 p-3 text-[9px] leading-5 text-white/45 font-mono">{logs.length?logs.join("\n"):"No cron or signal log recorded."}</pre></div></section>

  <section className="mx-auto max-w-7xl px-5 pb-6"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] p-4"><div className="flex items-center justify-between"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">Signal history</div><div className="mt-1 text-sm font-semibold">V28 trade history</div></div><div className="text-[8px] text-white/25">{history.length} records</div></div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-[9px]"><thead><tr className="border-b border-white/[0.07] text-white/25"><th className="py-2 pr-3">Time</th><th className="py-2 pr-3">Pair</th><th className="py-2 pr-3">Direction</th><th className="py-2 pr-3">Type</th><th className="py-2 pr-3">Entry</th><th className="py-2 pr-3">SL</th><th className="py-2 pr-3">R1</th><th className="py-2 pr-3">R1.5</th><th className="py-2 pr-3">R2</th><th className="py-2 pr-3">Status</th></tr></thead><tbody>{history.slice().sort((a,b)=>b.timestamp-a.timestamp).slice(0,50).map((h,i)=><tr key={`${h.id||h.pair}-${h.timestamp}-${i}`} className="border-b border-white/[0.04] text-white/55"><td className="py-2 pr-3 whitespace-nowrap">{new Date(h.timestamp).toLocaleString()}</td><td className="py-2 pr-3 font-semibold text-white/70">{h.pair}</td><td className={`py-2 pr-3 font-bold ${h.direction==="LONG"?"text-green-400":"text-red-400"}`}>{h.direction}</td><td className="py-2 pr-3">{h.type}</td><td className="py-2 pr-3">{money(h.entry)}</td><td className="py-2 pr-3 text-red-300">{money(h.stop)}</td><td className="py-2 pr-3 text-green-300">{money(h.tp1)}</td><td className="py-2 pr-3 text-green-300">{money(h.tp2??h.target)}</td><td className="py-2 pr-3 text-green-300">{money(h.tp3)}</td><td className="py-2 pr-3">{h.status||"—"}{h.exitReason?` · ${h.exitReason}`:""}</td></tr>)}</tbody></table></div></div></section>

  <section className="mx-auto max-w-7xl px-5 pb-10"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] p-4"><div className="flex items-center gap-2"><Activity size={14} className="text-[#dc6b27]"/><div><div className="text-sm font-semibold">How to read the board</div><div className="text-[9px] text-white/30">V28 trades from the existing breakout system. Structure Shift is observation-only during this 48-hour test.</div></div></div><div className="mt-3 grid md:grid-cols-3 gap-2 text-[9px] text-white/40"><div><b className="text-white/65">Pre-trade</b><br/>Wait for V28 ENTRY_1 / ENTRY_2.</div><div><b className="text-white/65">Active</b><br/>Manage R1 → R1.5 → R2.</div><div><b className="text-white/65">Structure Shift</b><br/>New directional observation only — never a V28 gate.</div></div></div></section>
 </main>
}
function Badge({icon,text}:{icon:React.ReactNode;text:string}){return <span className="flex items-center gap-1.5 rounded-full border border-white/[0.08] bg-white/[0.02] px-2.5 py-1.5 text-white/35">{icon}{text}</span>}
function KV({l,v,tone}:{l:string;v:string;tone?:string}){return <div><div className="text-[8px] uppercase tracking-wider text-white/20">{l}</div><div className={`mt-0.5 font-mono ${tone==="green"?"text-green-400":tone==="red"?"text-red-400":"text-white/65"}`}>{v}</div></div>}
