"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Clock3, Radio, RefreshCw, ShieldCheck, Terminal, Zap } from "lucide-react";

type AlertState = "VALID" | "STALE" | "INVALID";
type Tone = "bull" | "bear" | "neutral";
interface Signal { id:string; pair:string; direction:"LONG"|"SHORT"; type:string; entry:number; stop:number; target:number; tp1?:number; tp2?:number; tp3?:number; rr:number; timestamp:number; expectedMove:number; context?:any; meta?:{status:string}; }
interface HistoryEntry extends Signal { status:string; exitReason?:string; exitPrice?:number; exitTimestamp?:number; slToEntryAt?:number; tp1HitAt?:number; tp2HitAt?:number; tp3HitAt?:number; }
interface MarketData { pair:string; price:number; trend:string; location:string; trigger:string; adx:number; rsi:number; stochK:number; stochD:number; trendlinePrice:number; distToTrendline:number|null; momentumState?:string; htfTrend?:string; ema5?:number; ema13?:number; ema5Prev?:number; ema13Prev?:number; fourH513?:{stage:string;label:string;direction:"BULLISH"|"BEARISH"|"NEUTRAL";ema5:number;ema13:number;spread:number;spreadPct:number;spreadAtr:number;spreadContracting:boolean;spreadChangePct:number;ema5Slope:number;ema13Slope:number;crossNow:boolean;closedCandleTimestamp:number}; }
interface LatestAlert extends HistoryEntry { validity:{state:AlertState;reason:string}; currentPrice:number; ageMinutes:number; }
interface SystemState { version?:number; lastCronRun:number; lastCronAgeMs:number|null; activePositions:number; }

const PAIRS=["BTC","ETH","SOL","HYPE"];
const KRAKEN_PAIRS:Record<string,string>={BTC:"XBTUSD",ETH:"ETHUSD",SOL:"SOLUSD",HYPE:"HYPEUSD"};
const money=(n?:number)=>typeof n==="number"&&Number.isFinite(n)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n>=1000?0:n>=1?2:4}).format(n):"—";
const timeAgo=(ts?:number)=>{if(!ts)return"—";const m=Math.max(0,Math.floor((Date.now()-ts)/60000));if(m<1)return"just now";if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ${m%60}m ago`;return`${Math.floor(m/1440)}d ago`};
async function livePrice(pair:string){try{const r=await fetch(`https://api.kraken.com/0/public/Ticker?pair=${KRAKEN_PAIRS[pair]}`,{cache:"no-store"});const d=await r.json();if(d.error?.length)return null;return parseFloat(d.result[Object.keys(d.result)[0]].c[0])}catch{return null}}
function statusClass(s:AlertState){return s==="VALID"?"border-green-500/30 bg-green-500/10 text-green-300":s==="INVALID"?"border-red-500/30 bg-red-500/10 text-red-300":"border-yellow-500/30 bg-yellow-500/10 text-yellow-300"}
function toneClass(t:Tone|string){return t==="bull"?"text-green-400":t==="bear"?"text-red-400":"text-white/45"}
function stageValues(a:LatestAlert){return{tp1:a.tp1??a.context?.stages?.tp1,tp2:a.tp2??a.context?.stages?.tp2??a.target,tp3:a.tp3??a.context?.stages?.tp3}}
function milestoneClass(hit:boolean,active?:boolean){return hit?"border-green-400/40 bg-green-400/15 text-green-300":active?"border-yellow-400/40 bg-yellow-400/10 text-yellow-200":"border-white/[0.08] bg-white/[0.02] text-white/30"}
function directionTone(m?:MarketData):Tone{if(m?.trend?.startsWith("LONG"))return"bull";if(m?.trend?.startsWith("SHORT"))return"bear";return"neutral"}
function stateOfPlay(m?:MarketData){
 if(!m)return{title:"WAITING FOR DATA",detail:"No market snapshot is available yet.",waiting:"Fresh market analysis",tone:"neutral" as Tone};
 const tone=directionTone(m),long=tone==="bull",short=tone==="bear",r=m.rsi??50,k=m.stochK??50,d=m.stochD??50,dist=Math.abs(m.distToTrendline??0),near=dist<=2.5;
 if(m.location==="TL_INVALIDATED")return{title:"TL INVALIDATED",detail:"The current 4H V28 trendline has been broken. Waiting for a new valid 4H structure.",waiting:"New 4H structure → V28 retest",tone};
 const hotLong=long&&(r>=80||k>=90||d>=90),hotShort=short&&(r<=20||k<=10||d<=10);
 if(hotLong)return{title:"EXTENDED · WAIT FOR RESET",detail:`Trend is strong, but momentum is overheated (RSI ${r.toFixed(1)} · Stoch ${k.toFixed(1)}/${d.toFixed(1)}). This is chase territory, not an early entry.`,waiting:"Pullback → retest → momentum reset",tone};
 if(hotShort)return{title:"EXTENDED · WAIT FOR RESET",detail:`Bearish momentum is stretched (RSI ${r.toFixed(1)} · Stoch ${k.toFixed(1)}/${d.toFixed(1)}). Fresh shorts risk a squeeze.`,waiting:"Bounce/retest → rejection → momentum reset",tone};
 if(near&&m.trigger==="READY")return{title:long?"LONG TRADE NEAR":short?"SHORT TRADE NEAR":"TRADE NEAR",detail:`${dist.toFixed(2)}% from the 4H trendline with the V28 trigger ready. This is the area we want to watch closely.`,waiting:long?"V28 confirmation → ENTRY":short?"V28 confirmation → SHORT":"Trigger confirmation",tone};
 if(near)return{title:"RETEST IN PLAY",detail:`${dist.toFixed(2)}% from the 4H trendline. Price is close enough for a structural retest to matter.`,waiting:long?"Bullish reaction → V28 entry":short?"Bearish rejection → V28 entry":"Directional confirmation",tone};
 if(m.location==="BEYOND_TL")return{title:long?"BREAKOUT · WAIT FOR RETEST":short?"BREAKDOWN · WAIT FOR RETEST":"STRUCTURE BROKEN",detail:long?`Price is ${dist.toFixed(1)}% beyond the 4H trendline. The move is established; the higher-quality opportunity is a controlled retest rather than chasing.`:short?`Price is ${dist.toFixed(1)}% beyond the 4H trendline. Wait for a failed retest before treating the breakdown as actionable.`:"Price has moved beyond the tracked structure. Wait for confirmation.",waiting:long?"Pullback into structure → V28 retest":short?"Retest from below → V28 short":"Structure confirmation",tone};
 if(long)return{title:"BULLISH · SETUP DEVELOPING",detail:`1D bias is bullish with ADX ${m.adx.toFixed(1)}. Price is ${dist.toFixed(1)}% from the 4H trendline.`,waiting:"Structural test → V28 entry conditions",tone};
 if(short)return{title:"BEARISH · SETUP DEVELOPING",detail:`1D bias is bearish with ADX ${m.adx.toFixed(1)}. Price is ${dist.toFixed(1)}% from the 4H trendline.`,waiting:"Structural test → V28 entry conditions",tone};
 return{title:"NEUTRAL · WATCHING",detail:"No clean directional edge is active yet.",waiting:"Wait for directional confirmation",tone:"neutral" as Tone};
}
function timeframeRead(m?:MarketData){if(!m)return"Higher-timeframe read unavailable";const t=directionTone(m);const bias=t==="bull"?"1D BULLISH":t==="bear"?"1D BEARISH":"1D NEUTRAL";const structure=m.location==="TL_INVALIDATED"?"4H STRUCTURE INVALIDATED":m.location==="BEYOND_TL"?"4H STRUCTURE BROKEN":m.location==="NEAR_TL"?"4H STRUCTURE NEAR":"4H STRUCTURE WATCH";return`${bias} · ${structure}`}
function emaRead(m?:MarketData){if(!m?.ema5||!m?.ema13)return null;const bullish=m.ema5>m.ema13;const crossed=typeof m.ema5Prev==="number"&&typeof m.ema13Prev==="number"?((m.ema5Prev<=m.ema13Prev&&bullish)||(m.ema5Prev>=m.ema13Prev&&!bullish)):false;return`${crossed?"CROSS NOW · ":""}${bullish?"5 EMA ABOVE 13 EMA":"5 EMA BELOW 13 EMA"}`}
function ema513Read(m?:MarketData){const e=m?.fourH513;if(!e)return null;const bull=e.direction==="BULLISH",bear=e.direction==="BEARISH";return{tone:bull?"bull" as Tone:bear?"bear" as Tone:"neutral" as Tone,title:e.label}}

export default function Dashboard(){
 const[signals,setSignals]=useState<Record<string,Signal|null>>({}),[history,setHistory]=useState<HistoryEntry[]>([]),[market,setMarket]=useState<Record<string,MarketData>>({}),[latest,setLatest]=useState<Record<string,LatestAlert>>({}),[prices,setPrices]=useState<Record<string,number>>({}),[logs,setLogs]=useState<string[]>([]),[system,setSystem]=useState<SystemState|null>(null),[loading,setLoading]=useState(true),[lastFetch,setLastFetch]=useState(0),[resetting,setResetting]=useState<string|null>(null);
 async function load(){try{const r=await fetch("/api/signals",{cache:"no-store"});const d=await r.json();const s:Record<string,Signal|null>={},m:Record<string,MarketData>={};for(const p of PAIRS)s[p]=d.activeSignals?.find((x:Signal)=>x.pair===p)||null;for(const x of d.marketData||[])if(x?.pair)m[x.pair]=x;setSignals(s);setHistory(d.signalHistory||[]);setMarket(m);setLatest(d.latestAlerts||{});setLogs(d.logs||[]);setSystem(d.system||null);setLastFetch(Date.now())}catch(e){console.error("CXSwitch load failed",e)}finally{setLoading(false)}}
 async function resetCard(pair:string){if(resetting)return;setResetting(pair);try{const r=await fetch("/api/symbol-reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pair})});if(!r.ok)throw new Error(`Reset failed (${r.status})`);await load()}catch(e){console.error("CXSwitch symbol reconciliation failed",e)}finally{setResetting(null)}}
 useEffect(()=>{load();const i=setInterval(load,30000);return()=>clearInterval(i)},[]);
 useEffect(()=>{async function lp(){const n:Record<string,number>={};await Promise.all(PAIRS.map(async p=>{const x=await livePrice(p);if(x)n[p]=x}));setPrices(n)}lp();const i=setInterval(lp,10000);return()=>clearInterval(i)},[]);
 const strong=Object.values(market).filter(m=>m.trend?.includes("STRONG")).length,active=system?.activePositions??Object.values(signals).filter(Boolean).length,recent=useMemo(()=>history.slice().sort((a,b)=>b.timestamp-a.timestamp).slice(0,12),[history]);
 if(loading)return <main className="min-h-screen bg-[#070707] text-white flex items-center justify-center"><span className="text-sm text-white/35">Loading CXSwitch…</span></main>;
 return <main className="min-h-screen bg-[#070707] text-white">
  <nav className="border-b border-white/[0.08]"><div className="mx-auto max-w-7xl px-5 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-[#dc6b27] text-black flex items-center justify-center font-black">CX</div><div><div className="text-sm font-bold tracking-[0.18em]">CXSWITCH</div><div className="text-[9px] text-white/20 uppercase tracking-widest">Personal trading console</div></div></div><div className="flex gap-2 text-[9px]"><Badge icon={<Radio size={11}/>} text="LIVE · 10s"/><Badge icon={<Clock3 size={11}/>} text={`CRON ${system?.lastCronRun?timeAgo(system.lastCronRun):"—"}`}/><Badge icon={<ShieldCheck size={11}/>} text="MANUAL"/></div></div></nav>
  <section className="border-b border-white/[0.08]"><div className="mx-auto max-w-7xl px-5 py-5"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#dc6b27]/20 bg-[#dc6b27]/[0.06] px-3 py-1.5 text-[9px] uppercase tracking-[0.16em] text-[#dc6b27]"><span className="h-1.5 w-1.5 rounded-full bg-[#dc6b27]"/>CXSwitch v{system?.version??1} · V28 entry architecture · 5/13 daily bias</div><div className="grid grid-cols-2 md:grid-cols-4 gap-px overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.08]"><Stat label="SYSTEM" value={system?.lastCronRun&&system.lastCronAgeMs!==null&&system.lastCronAgeMs<1200000?"RUNNING":"CHECK"} detail={system?.lastCronRun?`Last analysis ${timeAgo(system.lastCronRun)}`:"No run recorded"} icon={<Activity size={15}/>}/><Stat label="TRACKING" value={`${PAIRS.length} MARKETS`} detail={`${strong} strong trend${strong===1?"":"s"}`} icon={<GaugeIcon/>}/><Stat label="WORKING" value={`${active} ACTIVE`} detail="Local trade state" icon={<Zap size={15}/>}/><Stat label="EXECUTION" value="MANUAL" detail="No exchange credentials" icon={<ShieldCheck size={15}/>}/></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-6"><div className="flex justify-between items-end mb-4"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">Market board</div><h1 className="mt-1 text-lg font-semibold">Latest alert + current market</h1></div><div className="text-[9px] text-white/20">Updated {lastFetch?new Date(lastFetch).toLocaleTimeString():"—"}</div></div>
   <div className="grid gap-px overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.08] md:grid-cols-2 xl:grid-cols-4">{PAIRS.map(pair=>{const m=market[pair],a=latest[pair],price=prices[pair]??m?.price??a?.entry??0,play=stateOfPlay(m),stages=a?stageValues(a):{tp1:undefined,tp2:undefined,tp3:undefined},ema=emaRead(m),diag=ema513Read(m),dirTone=directionTone(m);return <article key={pair} className="bg-[#0b0b0b] p-4 min-h-[440px] flex flex-col">
    <div className="flex items-start justify-between gap-3"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">{pair}/USD</div><div className="mt-1 text-2xl font-semibold">{money(price)}</div></div><div className={`text-[9px] font-bold uppercase tracking-widest text-right ${toneClass(dirTone)}`}>{m?.trend||"—"}</div></div>
    <div className={`mt-3 rounded-xl border p-3 ${play.tone==="bull"?"border-green-500/15 bg-green-500/[0.04]":play.tone==="bear"?"border-red-500/15 bg-red-500/[0.04]":"border-white/[0.07] bg-white/[0.02]"}`}><div className={`text-sm font-bold ${toneClass(play.tone)}`}>{play.title}</div><div className="mt-1 text-[10px] leading-relaxed text-white/50">{play.detail}</div><div className="mt-2 flex items-start gap-2 border-t border-white/[0.06] pt-2"><span className="text-[8px] uppercase tracking-widest text-white/20 shrink-0">Waiting for</span><span className={`text-[9px] font-semibold ${toneClass(play.tone)}`}>{play.waiting}</span></div></div>
    {diag&&<div className={`mt-3 rounded-xl border p-3 ${diag.tone==="bull"?"border-green-500/20 bg-green-500/[0.04]":diag.tone==="bear"?"border-red-500/20 bg-red-500/[0.04]":"border-white/[0.07] bg-white/[0.02]"}`}><div className="text-[8px] uppercase tracking-widest text-white/20">4H 5/13 diagnostic · closed candle</div><div className={`mt-1 text-[11px] font-bold ${toneClass(diag.tone)}`}>{diag.title}</div></div>}
    <div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.015] p-3"><div className="text-[8px] uppercase tracking-widest text-white/20 mb-2">State of play</div><div className="text-[9px] font-semibold text-white/65">{timeframeRead(m)}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[9px]"><span className={m?.trigger==="READY"?"text-green-400 font-semibold":"text-white/35"}>{m?.trigger==="READY"?"● V28 trigger ready":"○ V28 trigger waiting"}</span><span className={m?.location==="NEAR_TL"?"text-green-400":"text-white/35"}>{m?.location==="NEAR_TL"?"● Trade nearby":`○ ${m?.location||"Structure watch"}`}</span>{ema&&<span className={ema.includes("ABOVE")?"text-green-400":"text-red-400"}>○ {ema}</span>}</div></div>
    <div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-[9px]"><KV l="Trend" v={m?.trend||"—"} tone={dirTone==="bull"?"green":dirTone==="bear"?"red":""}/><KV l="Location" v={m?.location||"—"}/><KV l="ADX" v={m?.adx?.toFixed(1)||"—"}/><KV l="RSI" v={m?.rsi?.toFixed(1)||"—"}/><KV l="Stoch K/D" v={m?`${m.stochK.toFixed(1)} / ${m.stochD.toFixed(1)}`:"—"}/><KV l="4H TL" v={m?.trendlinePrice?money(m.trendlinePrice):"—"}/></div>
    {a?<div className={`mt-3 rounded-xl border p-3 ${a.validity.state==="VALID"?"border-green-500/20 bg-green-500/[0.04]":"border-white/[0.07] bg-white/[0.02]"}`}><div className="flex items-center justify-between"><span className="text-[9px] uppercase tracking-widest text-white/30">Latest alert · {a.type}</span><span className={`rounded-full border px-2 py-1 text-[9px] font-bold ${statusClass(a.validity.state)}`}>{a.validity.state}</span></div><div className={`mt-1 text-[9px] font-semibold ${a.direction==="LONG"?"text-green-400":"text-red-400"}`}>{a.direction} · {timeAgo(a.timestamp)}</div><div className="mt-2 grid grid-cols-2 gap-2"><KV l="Entry" v={money(a.entry)}/><KV l="R:R" v={a.rr?.toFixed(2)||"—"}/><KV l="SL" v={money(a.stop)} tone="red"/><KV l="TP1" v={money(stages.tp1??a.target)} tone="green"/><KV l="TP2" v={stages.tp2!==undefined?money(stages.tp2):"—"} tone="green"/><KV l="TP3" v={stages.tp3!==undefined?money(stages.tp3):"—"} tone="green"/></div><div className="mt-3 border-t border-white/[0.06] pt-3"><div className="text-[8px] uppercase tracking-widest text-white/20 mb-2">Management milestones</div><div className="flex flex-wrap gap-1.5"><span className={`rounded-md border px-2 py-1 text-[8px] font-semibold ${milestoneClass(!!a.slToEntryAt)}`}>{a.slToEntryAt?"✓ SL → ENTRY":"SL → ENTRY"}</span><span className={`rounded-md border px-2 py-1 text-[8px] font-semibold ${milestoneClass(!!a.tp1HitAt)}`}>{a.tp1HitAt?"✓ TP1 HIT":"TP1"}</span><span className={`rounded-md border px-2 py-1 text-[8px] font-semibold ${milestoneClass(!!a.tp2HitAt)}`}>{a.tp2HitAt?"✓ TP2 HIT":"TP2"}</span><span className={`rounded-md border px-2 py-1 text-[8px] font-semibold ${milestoneClass(!!a.tp3HitAt)}`}>{a.tp3HitAt?"✓ TP3 HIT":"TP3"}</span></div><div className="mt-2 text-[8px] text-white/25">{a.slToEntryAt?`BE ${timeAgo(a.slToEntryAt)}`:a.tp1HitAt?`TP1 ${timeAgo(a.tp1HitAt)}`:"Waiting for TP1"}</div></div><div className={`mt-2 text-[9px] ${a.validity.state==="VALID"?"text-green-300/70":"text-white/35"}`}>{a.validity.reason}</div></div>:<div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3 text-[10px] text-white/35">No alert has been recorded for this market yet.</div>}
    <div className="mt-auto pt-3 flex items-center justify-between gap-2 text-[8px] text-white/20"><span>{m?.momentumState||m?.trigger||"WAITING"}</span><button type="button" onClick={()=>resetCard(pair)} disabled={resetting===pair} className="inline-flex items-center gap-1.5 rounded-md border border-white/[0.08] bg-white/[0.02] px-2 py-1.5 text-[8px] font-semibold uppercase tracking-wider text-white/40 transition hover:border-white/[0.16] hover:text-white/70 disabled:cursor-wait disabled:opacity-50" title="Hide this card's stale latest-alert presentation without deleting history or position state"><RefreshCw size={10} className={resetting===pair?"animate-spin":""}/>{resetting===pair?"SYNCING":"RESET / RE-SYNC"}</button></div>
   </article>})}</div></section>
  <section className="mx-auto max-w-7xl px-5 pb-8"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.08] flex items-center gap-2"><Terminal size={14} className="text-[#dc6b27]"/><div><div className="text-sm font-semibold">Cron / signal log</div><div className="text-[9px] text-white/25">Detailed engine diagnostics — no alert spam</div></div></div><div className="max-h-80 overflow-auto p-4 font-mono text-[9px] leading-5">{logs.length?logs.map((x,i)=><div key={i} className={`${x.includes("ERROR")?"text-red-400":x.includes("[ALERT]")||x.includes("[SIGNAL]")?"text-green-400":x.includes("[EMA 4H 5/13]")?"text-yellow-300":x.includes("[VALIDITY]")?"text-yellow-300":"text-white/35"}`}>{x}</div>):<div className="text-white/25">No cron diagnostics available yet.</div>}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-10"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.08]"><div className="text-sm font-semibold">Signal history</div><div className="text-[9px] text-white/25">Alerts actually sent — not every market scan</div></div><div className="overflow-x-auto"><table className="w-full text-[10px]"><thead className="text-[8px] uppercase tracking-widest text-white/20"><tr><th className="px-4 py-2 text-left">Pair</th><th className="px-4 py-2 text-left">Dir</th><th className="px-4 py-2 text-left">Type</th><th className="px-4 py-2 text-left">Entry</th><th className="px-4 py-2 text-left">Status</th><th className="px-4 py-2 text-left">Age</th></tr></thead><tbody className="divide-y divide-white/[0.05]">{recent.map(h=><tr key={h.id}><td className="px-4 py-2.5 font-mono font-semibold">{h.pair}</td><td className={`px-4 py-2.5 font-bold ${h.direction==="LONG"?"text-green-400":"text-red-400"}`}>{h.direction}</td><td className="px-4 py-2.5 text-white/45">{h.type}</td><td className="px-4 py-2.5 font-mono">{money(h.entry)}</td><td className="px-4 py-2.5"><span className={`px-1.5 py-0.5 rounded ${h.status==="ACTIVE"?"bg-green-500/10 text-green-300":h.status==="SL_HIT"?"bg-red-500/10 text-red-300":"bg-white/5 text-white/40"}`}>{h.status}</span></td><td className="px-4 py-2.5 text-white/25">{timeAgo(h.exitTimestamp||h.timestamp)}</td></tr>)}</tbody></table></div></div></section>
 </main>
}
function Badge({icon,text}:{icon:React.ReactNode;text:string}){return <span className="flex items-center gap-1.5 rounded-full border border-white/[0.08] bg-white/[0.02] px-2.5 py-1.5 text-white/35">{icon}{text}</span>}
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="bg-[#0b0b0b] p-3"><div className="flex items-center gap-2 text-white/25">{icon}<span className="text-[8px] uppercase tracking-widest">{label}</span></div><div className="mt-1 text-sm font-semibold">{value}</div><div className="mt-0.5 text-[8px] text-white/25">{detail}</div></div>}
function KV({l,v,tone}:{l:string;v:string;tone?:string}){return <div><div className="text-[8px] uppercase tracking-wider text-white/20">{l}</div><div className={`mt-0.5 font-mono ${tone==="green"?"text-green-400":tone==="red"?"text-red-400":"text-white/65"}`}>{v}</div></div>}
function GaugeIcon(){return <span className="text-[13px]">◉</span>}
