"use client";

import { useEffect,useMemo,useState } from "react";
import { Activity,Clock3,Radio,ShieldCheck,Terminal,Zap } from "lucide-react";

type AlertState="VALID"|"STALE"|"INVALID";
interface Signal{ id:string;pair:string;direction:"LONG"|"SHORT";type:string;entry:number;stop:number;target:number;tp1?:number;tp2?:number;tp3?:number;rr:number;timestamp:number;expectedMove:number;context?:any;meta?:{status:string}; }
interface HistoryEntry extends Signal{status:string;exitReason?:string;exitPrice?:number;exitTimestamp?:number;}
interface MarketData{pair:string;price:number;trend:string;location:string;trigger:string;adx:number;rsi:number;stochK:number;stochD:number;trendlinePrice:number;distToTrendline:number|null;}
interface LatestAlert extends HistoryEntry{validity:{state:AlertState;reason:string};currentPrice:number;ageMinutes:number;}
interface SystemState{version?:number;lastCronRun:number;lastCronAgeMs:number|null;activePositions:number;}
const PAIRS=["BTC","ETH","SOL","HYPE"];
const KRAKEN_PAIRS:Record<string,string>={BTC:"XBTUSD",ETH:"ETHUSD",SOL:"SOLUSD",HYPE:"HYPEUSD"};
const money=(n?:number)=>typeof n==="number"&&Number.isFinite(n)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n>=1000?0:n>=1?2:4}).format(n):"—";
const timeAgo=(ts?:number)=>{if(!ts)return"—";const m=Math.max(0,Math.floor((Date.now()-ts)/60000));if(m<1)return"just now";if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ${m%60}m ago`;return`${Math.floor(h/24)}d ago`};
async function livePrice(pair:string){try{const r=await fetch(`https://api.kraken.com/0/public/Ticker?pair=${KRAKEN_PAIRS[pair]}`,{cache:"no-store"});const d=await r.json();if(d.error?.length)return null;return parseFloat(d.result[Object.keys(d.result)[0]].c[0])}catch{return null}}
function readMarket(m?:MarketData){if(!m)return{title:"WAITING FOR DATA",detail:"No market snapshot yet.",tone:"neutral" as const};const long=m.trend?.startsWith("LONG"),short=m.trend?.startsWith("SHORT"),r=m.rsi??50,k=m.stochK??50,d=Math.abs(m.distToTrendline??0),a=m.adx??0;if(long){if(r>=80)return{title:"OVEREXTENDED",detail:`RSI ${r.toFixed(1)} — strong trend, but price is stretched. Chase risk is high.`,tone:"bull" as const};if(k>=85)return{title:"HOT · EXHAUSTION RISK",detail:`Stoch ${k.toFixed(1)} — momentum is overheated. Prefer pullback/retest entries.`,tone:"bull" as const};if(m.location==="NEAR_TL"&&m.trigger==="READY")return{title:"EARLY ENTRY ZONE",detail:"Near the trendline with the V28 trigger ready.",tone:"bull" as const};if(m.location==="NEAR_TL")return{title:"RETEST · ROOM TO MOVE",detail:"Close to structure; a clean retest can offer an early entry.",tone:"bull" as const};if(d>=5)return{title:"EXTENDED · ROOM MAY REMAIN",detail:`${d.toFixed(1)}% beyond the trendline. Trend is bullish, but entry quality is lower.`,tone:"bull" as const};return{title:"BULLISH · MOMENTUM",detail:`ADX ${a.toFixed(1)} · RSI ${r.toFixed(1)} · Stoch ${k.toFixed(1)}.`,tone:"bull" as const}}if(short){if(r<=20)return{title:"OVERSOLD",detail:`RSI ${r.toFixed(1)} — bearish trend is stretched. Fresh shorts carry squeeze risk.`,tone:"bear" as const};if(k<=15)return{title:"COLD · EXHAUSTION RISK",detail:`Stoch ${k.toFixed(1)} — downside momentum is overheated.`,tone:"bear" as const};if(m.location==="NEAR_TL"&&m.trigger==="READY")return{title:"EARLY SHORT ZONE",detail:"Near the trendline with the V28 trigger ready.",tone:"bear" as const};if(m.location==="NEAR_TL")return{title:"RETEST · ROOM TO FALL",detail:"Close to structure; a failed retest can offer an early short.",tone:"bear" as const};if(d>=5)return{title:"EXTENDED · DOWNSIDE MAY REMAIN",detail:`${d.toFixed(1)}% beyond the trendline. Entry quality is lower.`,tone:"bear" as const};return{title:"BEARISH · MOMENTUM",detail:`ADX ${a.toFixed(1)} · RSI ${r.toFixed(1)} · Stoch ${k.toFixed(1)}.`,tone:"bear" as const}}return{title:"NEUTRAL · WATCHING",detail:"No clean directional edge is active yet.",tone:"neutral" as const}}
function statusClass(s:AlertState){return s==="VALID"?"border-green-500/30 bg-green-500/10 text-green-300":s==="INVALID"?"border-red-500/30 bg-red-500/10 text-red-300":"border-yellow-500/30 bg-yellow-500/10 text-yellow-300"}
function toneClass(t:string){return t==="bull"?"text-green-400":t==="bear"?"text-red-400":"text-white/35"}
function stageValues(a:LatestAlert){return{tp1:a.tp1??a.context?.stages?.tp1,tp2:a.tp2??a.context?.stages?.tp2??a.target,tp3:a.tp3??a.context?.stages?.tp3};}

export default function Dashboard(){
 const[signals,setSignals]=useState<Record<string,Signal|null>>({});const[history,setHistory]=useState<HistoryEntry[]>([]);const[market,setMarket]=useState<Record<string,MarketData>>({});const[latest,setLatest]=useState<Record<string,LatestAlert>>({});const[prices,setPrices]=useState<Record<string,number>>({});const[logs,setLogs]=useState<string[]>([]);const[system,setSystem]=useState<SystemState|null>(null);const[loading,setLoading]=useState(true);const[lastFetch,setLastFetch]=useState(0);
 async function load(){try{const r=await fetch("/api/signals",{cache:"no-store"});const d=await r.json();const s:Record<string,Signal|null>={},m:Record<string,MarketData>={};for(const p of PAIRS)s[p]=d.activeSignals?.find((x:Signal)=>x.pair===p)||null;for(const x of d.marketData||[])if(x?.pair)m[x.pair]=x;setSignals(s);setHistory(d.signalHistory||[]);setMarket(m);setLatest(d.latestAlerts||{});setLogs(d.logs||[]);setSystem(d.system||null);setLastFetch(Date.now())}catch(e){console.error("CXSwitch load failed",e)}finally{setLoading(false)}}
 useEffect(()=>{load();const i=setInterval(load,30000);return()=>clearInterval(i)},[]);
 useEffect(()=>{async function lp(){const n:Record<string,number>={};await Promise.all(PAIRS.map(async p=>{const x=await livePrice(p);if(x)n[p]=x}));setPrices(n)}lp();const i=setInterval(lp,10000);return()=>clearInterval(i)},[]);
 const strong=Object.values(market).filter(m=>m.trend?.includes("STRONG")).length;const active=system?.activePositions??Object.values(signals).filter(Boolean).length;const recent=useMemo(()=>history.slice().sort((a,b)=>b.timestamp-a.timestamp).slice(0,12),[history]);
 if(loading)return <main className="min-h-screen bg-[#070707] text-white flex items-center justify-center"><span className="text-sm text-white/35">Loading CXSwitch…</span></main>;
 return <main className="min-h-screen bg-[#070707] text-white">
  <nav className="border-b border-white/[0.08]"><div className="mx-auto max-w-7xl px-5 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-[#dc6b27] text-black flex items-center justify-center font-black">CX</div><div><div className="text-sm font-bold tracking-[0.18em]">CXSWITCH</div><div className="text-[9px] text-white/20 uppercase tracking-widest">Personal trading console</div></div></div><div className="flex gap-2 text-[9px]"><Badge icon={<Radio size={11}/>} text="LIVE · 10s"/><Badge icon={<Clock3 size={11}/>} text={`CRON ${system?.lastCronRun?timeAgo(system.lastCronRun):"—"}`}/><Badge icon={<ShieldCheck size={11}/>} text="MANUAL"/></div></div></nav>
  <section className="border-b border-white/[0.08]"><div className="mx-auto max-w-7xl px-5 py-6"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#dc6b27]/20 bg-[#dc6b27]/[0.06] px-3 py-1.5 text-[9px] uppercase tracking-[0.16em] text-[#dc6b27]"><span className="h-1.5 w-1.5 rounded-full bg-[#dc6b27]"/>CXSwitch v{system?.version??62} · V28 entry architecture · 5/13 daily bias</div><div className="grid grid-cols-2 md:grid-cols-4 gap-px overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.08]"><Stat label="SYSTEM" value={system?.lastCronRun&&system.lastCronAgeMs!==null&&system.lastCronAgeMs<1200000?"RUNNING":"CHECK"} detail={system?.lastCronRun?`Last analysis ${timeAgo(system.lastCronRun)}`:"No run recorded"} icon={<Activity size={15}/>}/><Stat label="TRACKING" value={`${PAIRS.length} MARKETS`} detail={`${strong} strong trend${strong===1?"":"s"}`} icon={<GaugeIcon/>}/><Stat label="WORKING" value={`${active} ACTIVE`} detail="Local trade state" icon={<Zap size={15}/>}/><Stat label="EXECUTION" value="MANUAL" detail="No exchange credentials" icon={<ShieldCheck size={15}/>}/></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-6"><div className="flex justify-between items-end mb-4"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">Market board</div><h1 className="mt-1 text-lg font-semibold">Latest alert + current market</h1></div><div className="text-[9px] text-white/20">Updated {lastFetch?new Date(lastFetch).toLocaleTimeString():"—"}</div></div>
   <div className="grid gap-px overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.08] md:grid-cols-2 xl:grid-cols-4">{PAIRS.map(pair=>{const s=signals[pair],m=market[pair],a=latest[pair],price=prices[pair]??m?.price??a?.entry??0,read=readMarket(m),stages=a?stageValues(a):{tp1:undefined,tp2:undefined,tp3:undefined};return <article key={pair} className="bg-[#0b0b0b] p-4 min-h-[420px] flex flex-col">
    <div className="flex items-start justify-between"><div><div className="text-[9px] uppercase tracking-[0.18em] text-white/25">{pair}/USD</div><div className="mt-1 text-2xl font-semibold">{money(price)}</div></div><div className={`text-[9px] font-bold uppercase tracking-widest ${toneClass(read.tone)}`}>{m?.trend||"—"}</div></div>
    <div className="mt-3 flex items-center justify-between"><span className="text-[9px] uppercase tracking-widest text-white/25">Alert status</span>{a?<span className={`rounded-full border px-2 py-1 text-[9px] font-bold ${statusClass(a.validity.state)}`}>{a.validity.state}</span>:<span className="rounded-full border border-white/10 px-2 py-1 text-[9px] text-white/30">NO ALERT</span>}</div>
    <div className={`mt-3 rounded-xl border p-3 ${read.tone==="bull"?"border-green-500/15 bg-green-500/[0.04]":read.tone==="bear"?"border-red-500/15 bg-red-500/[0.04]":"border-white/[0.07] bg-white/[0.02]"}`}><div className={`text-sm font-bold ${toneClass(read.tone)}`}>{read.title}</div><div className="mt-1 text-[10px] leading-relaxed text-white/45">{read.detail}</div></div>
    <div className="mt-3 grid grid-cols-2 gap-2 text-[9px]"><KV l="Trend" v={m?.trend||"—"} tone={m?.trend?.startsWith("LONG")?"green":m?.trend?.startsWith("SHORT")?"red":""}/><KV l="Location" v={m?.location||"—"}/><KV l="ADX" v={m?.adx?.toFixed(1)||"—"}/><KV l="RSI" v={m?.rsi?.toFixed(1)||"—"}/><KV l="Stoch K/D" v={m?`${m.stochK.toFixed(1)} / ${m.stochD.toFixed(1)}`:"—"}/><KV l="4H TL" v={m?.trendlinePrice?money(m.trendlinePrice):"—"}/></div>
    {a&&a.validity.state==="VALID"?<div className="mt-3 rounded-xl border border-green-500/20 bg-green-500/[0.04] p-3"><div className="flex justify-between"><span className="text-[9px] uppercase tracking-widest text-white/35">ACTIONABLE TRADE · {a.type}</span><span className={`text-[9px] font-bold ${a.direction==="LONG"?"text-green-400":"text-red-400"}`}>{a.direction}</span></div><div className="mt-2 grid grid-cols-2 gap-2"><KV l="Entry" v={money(a.entry)}/><KV l="Age" v={timeAgo(a.timestamp)}/><KV l="SL" v={money(a.stop)} tone="red"/><KV l="R:R" v={a.rr?.toFixed(2)}/><KV l="TP1" v={money(stages.tp1??a.target)} tone="green"/><KV l="TP2" v={stages.tp2!==undefined?money(stages.tp2):"—"} tone="green"/><KV l="TP3" v={stages.tp3!==undefined?money(stages.tp3):"—"} tone="green"/></div><div className="mt-2 text-[9px] text-green-300/60">Alert remains actionable · {a.validity.reason}</div></div>:a?<div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="flex items-center justify-between"><span className="text-[9px] uppercase tracking-widest text-white/25">Latest alert</span><span className={`text-[9px] font-bold ${statusClass(a.validity.state)} rounded-full border px-2 py-1`}>{a.validity.state}</span></div><div className="mt-2 text-[10px] text-white/35">{a.validity.reason}</div></div>:<div className="mt-3 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3 text-[10px] text-white/35">No alert has been recorded for this market yet.</div>}
    <div className="mt-auto pt-3 flex justify-between text-[8px] text-white/20"><span>{m?.trigger||"WAITING"}</span><span>{a?`Alert ${timeAgo(a.timestamp)}`:"Watching"}</span></div>
   </article>})}</div></section>
  <section className="mx-auto max-w-7xl px-5 pb-8"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.08] flex items-center gap-2"><Terminal size={14} className="text-[#dc6b27]"/><div><div className="text-sm font-semibold">Cron / signal log</div><div className="text-[9px] text-white/25">Detailed engine diagnostics — no alert spam</div></div></div><div className="max-h-80 overflow-auto p-4 font-mono text-[9px] leading-5">{logs.length?logs.map((x,i)=><div key={i} className={`${x.includes("ERROR")?"text-red-400":x.includes("[ALERT]")||x.includes("[SIGNAL]")?"text-green-400":x.includes("[VALIDITY]")?"text-yellow-300":"text-white/35"}`}>{x}</div>):<div className="text-white/25">No cron diagnostics available yet.</div>}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-10"><div className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.08]"><div className="text-sm font-semibold">Signal history</div><div className="text-[9px] text-white/25">Alerts actually sent — not every market scan</div></div><div className="overflow-x-auto"><table className="w-full text-[10px]"><thead className="text-[8px] uppercase tracking-widest text-white/20"><tr><th className="px-4 py-2 text-left">Pair</th><th className="px-4 py-2 text-left">Dir</th><th className="px-4 py-2 text-left">Type</th><th className="px-4 py-2 text-left">Entry</th><th className="px-4 py-2 text-left">Status</th><th className="px-4 py-2 text-left">Age</th></tr></thead><tbody className="divide-y divide-white/[0.05]">{recent.map(h=><tr key={h.id}><td className="px-4 py-2.5 font-mono font-semibold">{h.pair}</td><td className={`px-4 py-2.5 font-bold ${h.direction==="LONG"?"text-green-400":"text-red-400"}`}>{h.direction}</td><td className="px-4 py-2.5 text-white/45">{h.type}</td><td className="px-4 py-2.5 font-mono">{money(h.entry)}</td><td className="px-4 py-2.5"><span className={`px-1.5 py-0.5 rounded ${h.status==="ACTIVE"?"bg-green-500/10 text-green-300":h.status==="SL_HIT"?"bg-red-500/10 text-red-300":"bg-white/5 text-white/40"}`}>{h.status}</span></td><td className="px-4 py-2.5 text-white/25">{timeAgo(h.exitTimestamp||h.timestamp)}</td></tr>)}</tbody></table></div></div></section>
 </main>
}
function Badge({icon,text}:{icon:React.ReactNode;text:string}){return <span className="flex items-center gap-1.5 rounded-full border border-white/[0.08] bg-white/[0.02] px-2.5 py-1.5 text-white/35">{icon}{text}</span>}
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="bg-[#0b0b0b] p-3"><div className="flex items-center gap-2 text-white/25">{icon}<span className="text-[8px] uppercase tracking-widest">{label}</span></div><div className="mt-1 text-sm font-semibold">{value}</div><div className="mt-0.5 text-[8px] text-white/25">{detail}</div></div>}
function KV({l,v,tone}:{l:string;v:string;tone?:string}){return <div><div className="text-[8px] uppercase tracking-wider text-white/20">{l}</div><div className={`mt-0.5 font-mono ${tone==="green"?"text-green-400":tone==="red"?"text-red-400":"text-white/65"}`}>{v}</div></div>}
function GaugeIcon(){return <span className="text-[13px]">◉</span>}
