import { Redis } from "./supabase-kv";
import { TrendEngineResult } from "./1d-trend-engine";
const redis=new Redis();
// V2 namespace intentionally resets the seven-day diagnostic after the stale-candle fix.
const STATE_KEY="cxswitch:1d_trend_state_v2"; const LOG_KEY="cxswitch:1d_trend_log_v3"; const LOG_MAX=200;
export interface TrendStateRecord{state:string;candidateState:string;candidateStreak:number;lastObservation:number;lastEvaluatedAt:number;lastFlipAt?:number;flipCount:number;startedAt:number;}
export async function record1DUnavailable(pair:string,v28Active:any[],required:number,actual:number){const all=await redis.get<Record<string,TrendStateRecord>>(STATE_KEY)||{},prev=all[pair],now=Date.now();const record:TrendStateRecord={state:"INSUFFICIENT",candidateState:"INSUFFICIENT",candidateStreak:0,lastObservation:0,lastEvaluatedAt:now,lastFlipAt:prev?.lastFlipAt,flipCount:prev?.flipCount||0,startedAt:prev?.startedAt||now};all[pair]=record;await redis.set(STATE_KEY,all);if(prev?.state!=="INSUFFICIENT"){const history=await redis.get<any[]>(LOG_KEY)||[];history.push({timestamp:now,pair,event:"INSUFFICIENT",state:"INSUFFICIENT",previousState:prev?.state,candidateState:"INSUFFICIENT",candidateStreak:0,newDailyObservation:false,requiredDailyCandles:required,actualDailyCandles:actual,v28Active:v28Active.map(x=>({id:x.id,pair:x.pair,direction:x.direction,type:x.type,entry:x.entry,stop:x.stop,tp1:x.tp1,tp2:x.tp2,timestamp:x.timestamp}))});if(history.length>LOG_MAX)history.splice(0,history.length-LOG_MAX);await redis.set(LOG_KEY,history);}return{state:"INSUFFICIENT",candidateState:"INSUFFICIENT"};}
export async function record1DTrend(pair:string,result:TrendEngineResult,v28Active:any[],observationTimestamp:number){const all=await redis.get<Record<string,TrendStateRecord>>(STATE_KEY)||{},prev=all[pair],now=Date.now();const isNewObservation=!prev||prev.lastObservation!==observationTimestamp;const streak=isNewObservation?(prev?.candidateState===result.candidateState?(prev.candidateStreak+1):1):(prev?.candidateStreak||1);let state=prev?.state||result.candidateState,flip=false;if(!prev)state=result.candidateState;else if(isNewObservation&&result.candidateState!==prev.state&&streak>=2){state=result.candidateState;flip=state!==prev.state;}all[pair]={state,candidateState:result.candidateState,candidateStreak:streak,lastObservation:observationTimestamp,lastEvaluatedAt:now,lastFlipAt:flip?now:prev?.lastFlipAt,flipCount:(prev?.flipCount||0)+(flip?1:0),startedAt:prev?.startedAt||now};await redis.set(STATE_KEY,all);const log:any={timestamp:now,observationTimestamp,pair,event:flip?"FLIP":"EVALUATION",state,previousState:prev?.state,candidateState:result.candidateState,candidateStreak:streak,newDailyObservation:isNewObservation,price:result.price,structure:result.structure,ema:result.ema,fast513:result.fast513,adx:result.adx,adxPrev:result.adxPrev,momentum:result.momentum,protectedLevel:result.protectedLevel,explanation:result.explanation,parameters:result.parameters,v28Active:v28Active.map(x=>({id:x.id,pair:x.pair,direction:x.direction,type:x.type,entry:x.entry,stop:x.stop,tp1:x.tp1,tp2:x.tp2,tp3:x.tp3,timestamp:x.timestamp}))};if(isNewObservation||flip){const history=await redis.get<any[]>(LOG_KEY)||[];history.push(log);if(history.length>LOG_MAX)history.splice(0,history.length-LOG_MAX);await redis.set(LOG_KEY,history);}if(flip)console.log(`[1D FLIP] ${pair} — ${prev?.state||"—"} -> ${state}`);return{flip,state};}
export async function get1DTrendState(){return(await redis.get<Record<string,TrendStateRecord>>(STATE_KEY))||{};}
export async function get1DTrendLog(){return(await redis.get<any[]>(LOG_KEY))||[];}
