import { Redis } from "@upstash/redis";
import { TrendEngineResult } from "./1d-trend-engine";
const redis=new Redis({url:process.env.KV_REST_API_URL!,token:process.env.KV_REST_API_TOKEN!});
const STATE_KEY="cxswitch:1d_trend_state_v1";
const LOG_KEY="cxswitch:1d_trend_log_v1";
export interface TrendStateRecord{state:string;candidateState:string;candidateStreak:number;lastEvaluatedAt:number;lastFlipAt?:number;flipCount:number;startedAt:number;}
export async function record1DTrend(pair:string,result:TrendEngineResult,v28Active:any[]){const all=await redis.get<Record<string,TrendStateRecord>>(STATE_KEY)||{};const prev=all[pair];const streak=prev?.candidateState===result.candidateState?(prev.candidateStreak+1):1;let state=prev?.state||result.candidateState;let flip=false;if(!prev){state=result.candidateState;}else if(result.candidateState!==prev.state&&streak>=2){state=result.candidateState;flip=state!==prev.state;}const now=Date.now();all[pair]={state,candidateState:result.candidateState,candidateStreak:streak,lastEvaluatedAt:now,lastFlipAt:flip?now:prev?.lastFlipAt,flipCount:(prev?.flipCount||0)+(flip?1:0),startedAt:prev?.startedAt||now};await redis.set(STATE_KEY,all);const log:any={timestamp:now,pair,event:flip?"FLIP":"EVALUATION",state,previousState:prev?.state,candidateState:result.candidateState,candidateStreak:streak,price:result.price,structure:result.structure,ema:result.ema,fast513:result.fast513,adx:result.adx,adxPrev:result.adxPrev,momentum:result.momentum,protectedLevel:result.protectedLevel,explanation:result.explanation,parameters:result.parameters,v28Active:v28Active.map(x=>({id:x.id,pair:x.pair,direction:x.direction,type:x.type,entry:x.entry,stop:x.stop,tp1:x.tp1,tp2:x.tp2,tp3:x.tp3,timestamp:x.timestamp}))};const history=await redis.get<any[]>(LOG_KEY)||[];history.push(log);if(history.length>2000)history.splice(0,history.length-2000);await redis.set(LOG_KEY,history);console.log(`[1D TREND] ${pair} — ${flip?`FLIP ${prev?.state} -> ${state}`:`EVALUATION state=${state}`} | candidate=${result.candidateState} streak=${streak} | ${result.explanation}`);return{flip,state};}
export async function get1DTrendState(){return(await redis.get<Record<string,TrendStateRecord>>(STATE_KEY))||{};}
export async function get1DTrendLog(){return(await redis.get<any[]>(LOG_KEY))||[];}
