// Independent ETH strategies. Kept separate from V28 so every alert carries its originating strategy.
import { Candle, Signal } from "./strategy";
type Rule=(z:Features)=>boolean;
interface Features{close:number;atr:number;rsi:number;roc:number;trend:1|-1;e5:number;e13:number;e20:number;e50:number;vol:number;bull:boolean;bear:boolean;}
interface StrategyConfig{name:string;source:string;longRules:Rule[];shortRules:Rule[];}
const avg=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const ema=(a:number[],p:number)=>{if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r};
function features(c:Candle[]):Features|null{if(c.length<60)return null;const cl=c.map(x=>x.close),e5=ema(cl,5),e13=ema(cl,13),e20=ema(cl,20),e50=ema(cl,50);let g=0,l=0;for(let i=Math.max(1,cl.length-14);i<cl.length;i++){const d=cl[i]-cl[i-1];if(d>0)g+=d;else l-=d}const rsi=l?100-100/(1+(g/14)/(l/14)):100;const tr:number[]=[];for(let i=Math.max(1,c.length-14);i<c.length;i++){const x=c[i],p=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)))}const atr=avg(tr),x=c.at(-1)!,range=x.high-x.low||1;return{close:x.close,atr,rsi,roc:(x.close-c[Math.max(0,c.length-7)].close)/(atr||x.close),trend:e20.at(-1)!>e50.at(-1)!?1:-1,e5:e5.at(-1)!,e13:e13.at(-1)!,e20:e20.at(-1)!,e50:e50.at(-1)!,vol:x.volume/(avg(c.slice(-21,-1).map(z=>z.volume))||x.volume),bull:x.close>x.open&&Math.abs(x.close-x.open)/range>=.4,bear:x.close<x.open&&Math.abs(x.close-x.open)/range>=.4};}
const CONFIGS:StrategyConfig[]=[
 {name:"ETH Trend Aligned",source:"ETH_RESEARCH_01_TREND",longRules:[z=>z.trend===1],shortRules:[z=>z.trend===-1]},
 {name:"ETH Positive Momentum",source:"ETH_RESEARCH_02_MOMENTUM",longRules:[z=>z.roc>0],shortRules:[z=>z.roc<0]},
 {name:"ETH High Volatility",source:"ETH_RESEARCH_03_VOLATILITY",longRules:[z=>z.vol>=1.2],shortRules:[z=>z.vol>=1.2]},
];
export function getIndependentStrategyConfigs(){return CONFIGS.flatMap(x=>[{name:x.name,source:x.source,direction:"LONG" as const},{name:x.name,source:x.source,direction:"SHORT" as const}]);}
export function generateIndependentSignals(pair:string,candles4h:Candle[],currentPrice:number):Signal[]{if(pair!=="ETH")return[];const completed=candles4h.length>1?candles4h.slice(0,-1):candles4h,z=features(completed);if(!z)return[];const prev=completed.slice(0,-1),p=features(prev);if(!p)return[];const longTrigger=z.bull||z.e5>z.e13&&p.e5<=p.e13;const shortTrigger=z.bear||z.e5<z.e13&&p.e5>=p.e13;if(!longTrigger&&!shortTrigger)return[];const ts=completed.at(-1)!.timestamp;const signals:Signal[]=[];for(const c of CONFIGS){if(longTrigger&&c.longRules.every(r=>r(z))){const entry=currentPrice,risk=Math.max(1.5*z.atr,entry*.008),stop=entry-risk,target=entry+2*risk;signals.push({id:`${c.source}_ETH_LONG_${ts}`,pair:"ETH",direction:"LONG",type:"ENTRY_1",scale:"ENTRY_1",entry,stop,target,tp1:entry+risk,tp2:target,tp3:target,confidence:Math.min(99,55+Math.max(0,Math.abs(z.roc)*10)),rr:2,adx:0,rsi:z.rsi,stochK:0,stochD:0,expectedMove:Math.round(Math.abs(target-entry)/entry*1000)/10,reason:`Independent ${c.name} LONG fired on completed 4H candle`,timestamp:Date.now(),version:29,trend:z.trend===1?"BULLISH":"BEARISH",location:c.name,trigger:"INDEPENDENT_4H",context:{strategySource:c.source,strategyName:c.name,direction:"LONG",engine:"INDEPENDENT",rules:c.longRules.length,features:{rsi:z.rsi,roc:z.roc,trend:z.trend,ema20:z.e20,atr:z.atr,volumeRatio:z.vol},signalCandleTimestamp:ts,v28Compatible:false}} as Signal);}
if(shortTrigger&&c.shortRules.every(r=>r(z))){const entry=currentPrice,risk=Math.max(1.5*z.atr,entry*.008),stop=entry+risk,target=entry-risk;signals.push({id:`${c.source}_ETH_SHORT_${ts}`,pair:"ETH",direction:"SHORT",type:"ENTRY_1",scale:"ENTRY_1",entry,stop,target,tp1:entry-risk,tp2:target,tp3:target,confidence:Math.min(99,55+Math.max(0,Math.abs(z.roc)*10)),rr:2,adx:0,rsi:z.rsi,stochK:0,stochD:0,expectedMove:Math.round(Math.abs(target-entry)/entry*1000)/10,reason:`Independent ${c.name} SHORT fired on completed 4H candle`,timestamp:Date.now(),version:29,trend:z.trend===1?"BULLISH":"BEARISH",location:c.name,trigger:"INDEPENDENT_4H",context:{strategySource:c.source,strategyName:c.name,direction:"SHORT",engine:"INDEPENDENT",rules:c.shortRules.length,features:{rsi:z.rsi,roc:z.roc,trend:z.trend,ema20:z.e20,atr:z.atr,volumeRatio:z.vol},signalCandleTimestamp:ts,v28Compatible:false}} as Signal);}}
return signals;}
