// lib/strategy.ts — V28 early-breakout core
// ============================================================
// V28 is deliberately simple:
//   ENTRY_1 = first confirmed 4H trendline breakout (early entry)
//   ENTRY_2 = independent breakout retest when no position was captured
//   ADD     = breakout retest/continuation after ENTRY_1 or ENTRY_2 is active
// 1D 5/13 is context only; it never gates a genuine 4H breakout.
// The separate 1D experiment is diagnostic only.

import { get4HEmaDiagnostic } from "./ema-diagnostic";

export interface Candle { timestamp:number; open:number; high:number; low:number; close:number; volume:number; }
export interface BreakoutRecord { direction:"LONG"|"SHORT"; price:number; timestamp:number; candleIndex:number; }
export interface Signal { id:string; pair:string; direction:"LONG"|"SHORT"; type:"ENTRY_1"|"ENTRY_2"|"ADD"; scale:"ENTRY_1"|"ENTRY_2"|"ADD"|null; entry:number; stop:number; target:number; tp1?:number; tp2?:number; tp3?:number; confidence:number; rr:number; adx:number; rsi:number; stochK:number; stochD:number; expectedMove:number; reason:string; timestamp:number; version:number; trend?:string; location?:string; trigger?:string; context?:any; }
export interface SignalResult { signals?:Signal[]; signal?:Signal; market?:any; debug:string[]; }
export const CURRENT_SIGNAL_VERSION=1;

const DAILY_FAST=5, DAILY_SLOW=13, TF_FAST=8, TF_SLOW=21;
const BREAKOUT_PCT=0.005, RETEST_PCT=0.012, ENTRY_ATR=2, ADD_ATR=1.5, MIN_RR=1.25;
const STALE_TL_PCT=0.04, FRESH_LOOKBACK=30, BREAKOUT_EXPIRY_CANDLES=12;
const LEVERAGE=20, MMR=0.01, LIQ_BUFFER=0.005;

type Pivot={index:number;price:number;timestamp:number};
type TL={valid:boolean;slope:number;intercept:number;price:number;pivots:Pivot[];ageCandles:number;reason:string;invalidated:boolean;stale:boolean};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r;}
function atr(c:Candle[],p=14){const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));}return avg(r);}
function rsi(a:number[],p=14){if(a.length<2)return 50;let g=0,l=0,n=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l+=Math.abs(d);n++;}if(!n)return 50;const ag=g/n,al=l/n;if(al===0)return 100;return 100-100/(1+ag/al);}
function rsiSeries(a:number[],p=14){const r:number[]=[];for(let i=p;i<a.length;i++)r.push(rsi(a.slice(i-p,i+1),p));return r;}
function stochRsi(a:number[],rp=14,sp=14,ks=3,ds=3){const rv=rsiSeries(a,rp);if(rv.length<sp+ks-1)return{k:50,d:50};const raw:number[]=[];for(let i=sp-1;i<rv.length;i++){const w=rv.slice(i-sp+1,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100);}const kv:number[]=[];for(let i=ks-1;i<raw.length;i++)kv.push(avg(raw.slice(i-ks+1,i+1)));if(kv.length<ds)return{k:50,d:50};return{k:Math.round(kv.at(-1)!*10)/10,d:Math.round(avg(kv.slice(-ds))*10)/10};}
function wilder(a:number[],p:number){if(!a.length)return[];const r=[avg(a.slice(0,p))];for(let i=p;i<a.length;i++)r.push((r.at(-1)!*(p-1)+a[i])/p);return r;}
function adx(c:Candle[],p=14){if(c.length<p+1)return 0;const tr:number[]=[],plus:number[]=[],minus:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));plus.push(x.high-q.high>q.low-x.low?Math.max(x.high-q.high,0):0);minus.push(q.low-x.low>x.high-q.high?Math.max(q.low-x.low,0):0);}const t=wilder(tr,p),pd=wilder(plus,p),md=wilder(minus,p),dx:number[]=[];for(let i=0;i<t.length;i++){const a=pd[i]/t[i]*100,b=md[i]/t[i]*100;dx.push(a+b===0?0:Math.abs(a-b)/(a+b)*100);}return Math.round((wilder(dx,p).at(-1)||0)*10)/10;}
function daily(c:Candle[]){const m=new Map<string,Candle[]>();for(const x of [...c].sort((a,b)=>a.timestamp-b.timestamp)){const d=new Date(x.timestamp),k=`${d.getUTCFullYear()}-${d.getUTCMonth()}-${d.getUTCDate()}`;(m.get(k)||m.set(k,[]).get(k)!).push(x);}return[...m.values()].map(b=>({timestamp:b[0].timestamp,open:b[0].open,high:Math.max(...b.map(x=>x.high)),low:Math.min(...b.map(x=>x.low)),close:b.at(-1)!.close,volume:b.reduce((s,x)=>s+x.volume,0)}));}
function bias(c:Candle[]):"LONG"|"SHORT"|null{if(c.length<20)return null;const a=c.map(x=>x.close),f=ema(a,DAILY_FAST).at(-1)!,s=ema(a,DAILY_SLOW).at(-1)!;return f>s?"LONG":f<s?"SHORT":null;}
function strength(c:Candle[],d:"LONG"|"SHORT"){const h=c.slice(-20).map(x=>x.high),l=c.slice(-20).map(x=>x.low);return d==="LONG"&&h.at(-1)!>Math.max(...h.slice(0,-1))||d==="SHORT"&&l.at(-1)!<Math.min(...l.slice(0,-1))?"STRONG":"MEDIUM";}
function pivots(c:Candle[],kind:"HIGH"|"LOW",w=2){const r:Pivot[]=[];for(let i=w;i<c.length-w;i++){const v=kind==="LOW"?c[i].low:c[i].high;let ok=true;for(let j=1;j<=w;j++){if(kind==="LOW"?(v>=c[i-j].low||v>=c[i+j].low):(v<=c[i-j].high||v<=c[i+j].high)){ok=false;break;}}if(ok)r.push({index:i,price:v,timestamp:c[i].timestamp});}return r;}
function buildTrendline(c:Candle[],d:"LONG"|"SHORT",lookback=60):TL{const kind=d==="LONG"?"HIGH":"LOW";const p=pivots(c,kind).filter(x=>x.index>=Math.max(0,c.length-lookback)).slice(-5);if(p.length<2)return{valid:false,slope:0,intercept:0,price:0,pivots:p,ageCandles:p.length?c.length-1-p[0].index:0,reason:`No ${d} breakout trendline — ${p.length}/2 confirmed pivots`,invalidated:false,stale:false};const a=p.at(-2)!,b=p.at(-1)!,dx=b.index-a.index;if(dx<=0)return{valid:false,slope:0,intercept:0,price:0,pivots:p,ageCandles:0,reason:"Trendline degenerate",invalidated:false,stale:false};const slope=(b.price-a.price)/dx,intercept=a.price-slope*a.index,price=slope*(c.length-1)+intercept,buf=Math.max(Math.abs(price)*BREAKOUT_PCT,atr(c)*.35);let invalidated=false;for(let i=b.index+1;i<c.length-1;i++){const line=slope*i+intercept;if(d==="LONG"&&c[i].close>line+buf){invalidated=true;break;}if(d==="SHORT"&&c[i].close<line-buf){invalidated=true;break;}}const distance=Math.abs((c.at(-1)!.close-price)/Math.max(Math.abs(price),1));const stale=distance>=STALE_TL_PCT&&!invalidated;return{valid:true,slope,intercept,price,pivots:p,ageCandles:c.length-1-a.index,reason:stale?`${d} breakout trendline stale — ${Math.round(distance*100)/100}% away; rebuilding`:invalidated?`${d} breakout trendline already broken — preserving breakout context`:`${d} breakout trendline active`,invalidated,stale};}
function trendline(c:Candle[],d:"LONG"|"SHORT"):TL{const primary=buildTrendline(c,d,60);if(!primary.stale)return primary;const fresh=buildTrendline(c,d,FRESH_LOOKBACK);if(fresh.valid)return{...fresh,reason:`${fresh.reason}; fresh ${FRESH_LOOKBACK}-candle structure`};return primary;}
function lineAt(tl:TL,i:number){return tl.slope*i+tl.intercept;}
function opposite(pair:string,d:"LONG"|"SHORT",trades:any[]|undefined){return !!trades?.some(t=>(t.pair===pair||t.symbol===pair)&&t.direction===(d==="LONG"?"SHORT":"LONG"));}
function same(pair:string,d:"LONG"|"SHORT",trades:any[]|undefined){return !!trades?.some(t=>(t.pair===pair||t.symbol===pair)&&t.direction===d);}
function liq(entry:number,d:"LONG"|"SHORT"){return d==="LONG"?entry*(1-1/LEVERAGE+MMR):entry*(1+1/LEVERAGE-MMR);}
function round(n:number){return Math.round(n*100000)/100000;}
function snapshot(pair:string,c:Candle[],d:"LONG"|"SHORT",tl:TL,price:number){const closes=c.map(x=>x.close),st=stochRsi(closes),r=rsi(closes),a=adx(c),e8=ema(closes,TF_FAST).at(-1)!,e21=ema(closes,TF_SLOW).at(-1)!,d1=getDaily513Diagnostic(c);const dist=tl.valid?(price-tl.price)/tl.price:null;return{pair,price:round(price),timestamp:Date.now(),trend:`${d} ${strength(daily(c),d)}`,location:dist===null?"NO_TL":Math.abs(dist)<RETEST_PCT?"NEAR_TL":(d==="LONG"?price>tl.price:price<tl.price)?"BEYOND_TL":"FAR_FROM_TL",trigger:"WAITING",adx:a,rsi:Math.round(r*10)/10,stochK:st.k,stochD:st.d,trendlinePrice:tl.valid?round(tl.price):0,distToTrendline:dist===null?null:Math.round(Math.abs(dist)*10000)/100,ema8_4h:round(e8),ema21_4h:round(e21),fourH513:get4HEmaDiagnostic(c),daily513:d1,momentumState:d==="LONG"?(r>=80?"OVEREXTENDED":r>=70?"HOT":st.k<20?"PULLBACK":"NEUTRAL"):(r<=20?"OVEREXTENDED":r<=30?"HOT":st.k>80?"PULLBACK":"NEUTRAL"),trendlineStatus:tl.stale?"STALE_REBUILD":tl.valid?"ACTIVE":"REBUILDING",trendlineReason:tl.reason,trendlinePivots:tl.pivots.length,trendlineAgeCandles:tl.ageCandles,trendlineSlope:round(tl.slope)};}
export function getDaily513Diagnostic(c:Candle[]){const d=daily(c);if(d.length<21)return{stage:"NEUTRAL",label:"1D NEUTRAL",direction:"NEUTRAL" as const,ema5:0,ema13:0,spread:0,spreadPct:0,spreadContracting:false,spreadChangePct:0,ema5Slope:0,ema13Slope:0};const x=d.slice(0,-1).map(z=>z.close),f=ema(x,5),s=ema(x,13),ema5=f.at(-1)!,ema13=s.at(-1)!,p5=f.at(-2)!,p13=s.at(-2)!,spread=ema5-ema13,prev=p5-p13,contract=Math.abs(spread)<Math.abs(prev),earlyBullish=spread<0&&ema5>p5&&contract,earlyBearish=spread>0&&ema5<p5&&contract;let stage=spread>0?"BULLISH":"BEARISH",label=spread>0?"1D BULLISH":"1D BEARISH",direction:"BULLISH"|"BEARISH"="BULLISH";if(spread<0){direction="BEARISH";}else if(earlyBearish){stage="EARLY_BEARISH";label="1D EARLY BEARISH";}else if(earlyBullish){stage="EARLY_BULLISH";label="1D EARLY BULLISH";}return{stage,label,direction,ema5,ema13,spread,spreadPct:ema13?spread/ema13*100:0,spreadContracting:contract,spreadChangePct:prev?((Math.abs(spread)-Math.abs(prev))/Math.abs(prev))*100:0,ema5Slope:ema5-p5,ema13Slope:ema13-p13};}

export function generateSignal(pair:string,candles1h:Candle[],candles4h:Candle[],candles15m:Candle[],activeTrades?:any[],currentPrice?:number,lastBreakout?:BreakoutRecord):SignalResult{
 const debug:string[]=[];const now=Date.now();if(candles4h.length<30){debug.push("Insufficient 4H data");return{debug};}
 const d=daily(candles4h),contextDir=bias(d),price=currentPrice??candles4h.at(-1)!.close;
 const i=candles4h.length-1,prev=candles4h.at(-2)!,last=candles4h.at(-1)!;
 const prepare=(dir:"LONG"|"SHORT")=>{const primary=buildTrendline(candles4h,dir,60);const wasStale=primary.stale;const alreadyBeyond=primary.valid&&(dir==="LONG"?price>primary.price*1.02:price<primary.price*0.98);let tl=primary;if(wasStale){const fresh=buildTrendline(candles4h,dir,FRESH_LOOKBACK);if(fresh.valid)tl={...fresh,reason:`${fresh.reason}; fresh ${FRESH_LOOKBACK}-candle structure`};}const buf=tl.valid?Math.max(Math.abs(tl.price)*BREAKOUT_PCT,atr(candles4h)*.35):0;const freshBeyond=wasStale&&alreadyBeyond&&tl.valid&&(dir==="LONG"?price>tl.price+buf:price<tl.price-buf);return{tl,wasStale,alreadyBeyond,freshBeyond};};
 const LP=prepare("LONG"),SP=prepare("SHORT"),longTL=LP.tl,shortTL=SP.tl;
 const test=(dir:"LONG"|"SHORT",x:{tl:TL;freshBeyond:boolean})=>{const tl=x.tl;if(!tl.valid)return{breakout:false,retest:false,line:0,buf:0,dist:0,freshBeyond:false};const line=lineAt(tl,i),prevLine=lineAt(tl,i-1),buf=Math.max(Math.abs(line)*BREAKOUT_PCT,atr(candles4h)*.35);const broke=dir==="LONG"?last.close>line+buf&&prev.close<=prevLine+buf:last.close<line-buf&&prev.close>=prevLine-buf;const alreadyBeyondBuffer=dir==="LONG"?last.close>line+buf:last.close<line-buf;const retest=dir==="LONG"?last.low<=line*(1+RETEST_PCT)&&last.close>line&&last.close>=prev.close:last.high>=line*(1-RETEST_PCT)&&last.close<line&&last.close<=prev.close;return{breakout:broke||x.freshBeyond,retest,line,buf,dist:(price-line)/Math.max(Math.abs(line),1),freshBeyond:x.freshBeyond,alreadyBeyondBuffer};};
 const L=test("LONG",LP),S=test("SHORT",SP);let dir:"LONG"|"SHORT"|null=null,tl:TL|null=null,breakout=false,retest=false;
 if(L.breakout&&!S.breakout){dir="LONG";tl=longTL;breakout=true;}else if(S.breakout&&!L.breakout){dir="SHORT";tl=shortTL;breakout=true;}else if(L.retest&&!S.retest){dir="LONG";tl=longTL;retest=true;}else if(S.retest&&!L.retest){dir="SHORT";tl=shortTL;retest=true;}else if(contextDir){dir=contextDir;tl=dir==="LONG"?longTL:shortTL;}
 if(!dir||!tl){debug.push("No 4H structural direction");return{debug};}
 if(opposite(pair,dir,activeTrades)){debug.push("Opposite direction active");return{debug};}
 const has=same(pair,dir,activeTrades);
 debug.push(`[V28] ${pair} ${dir} | breakout TL ${tl.price?tl.price.toFixed(2):"—"} | price ${price.toFixed(2)} | 1D ${contextDir?strength(d,contextDir):"NEUTRAL"}`);
 debug.push(`[V28 BREAKOUT] lastBreakout=${lastBreakout?`${lastBreakout.direction}@${lastBreakout.price.toFixed(2)} candle=${lastBreakout.candleIndex} age=${i-lastBreakout.candleIndex}`:"NONE"}`);
 if(LP.freshBeyond||SP.freshBeyond)debug.push(`[V28] fresh stale handoff ${LP.freshBeyond?"LONG":"SHORT"} | oldTL beyond=${LP.freshBeyond?LP.alreadyBeyond:SP.alreadyBeyond}`);
 if(!tl.valid){debug.push(`State: ${tl.reason}`);return{market:snapshot(pair,candles4h,dir,tl,price),debug};}
 let type:"ENTRY_1"|"ENTRY_2"|"ADD"|null=null;
 if(breakout){type="ENTRY_1";}
 else if(retest){
   if(has){type="ADD";}
   else {
     const hasRecentBreakout=!!lastBreakout&&lastBreakout.direction===dir&&(i-lastBreakout.candleIndex)>=0&&(i-lastBreakout.candleIndex)<=BREAKOUT_EXPIRY_CANDLES;
     if(!hasRecentBreakout){debug.push("ENTRY_2 blocked: no recent recorded breakout");return{market:snapshot(pair,candles4h,dir,tl,price),debug};}
     const retestDistance=Math.abs(price-lastBreakout!.price)/Math.max(Math.abs(lastBreakout!.price),1);
     if(retestDistance>=0.01){debug.push("ENTRY_2 blocked: retest not of recorded breakout level");return{market:snapshot(pair,candles4h,dir,tl,price),debug};}
     type="ENTRY_2";
   }
 }
 const st=stochRsi(candles4h.map(x=>x.close)),r=Math.round(rsi(candles4h.map(x=>x.close))*10)/10,a=adx(candles4h);
 if(!type){debug.push(`State: ${has?"POST_BREAKOUT_WAIT":"WAITING"} | No signal`);return{market:snapshot(pair,candles4h,dir,tl,price),debug};}
 const av=atr(candles4h),entry=price,structural=dir==="LONG"?Math.min(...candles4h.slice(-10).map(x=>x.low),entry-av*(type==="ADD"?ADD_ATR:ENTRY_ATR)):Math.max(...candles4h.slice(-10).map(x=>x.high),entry+av*(type==="ADD"?ADD_ATR:ENTRY_ATR));const stop=structural,risk=Math.abs(entry-stop);if(!risk){debug.push("Zero risk");return{debug};}
 const tp1=dir==="LONG"?entry+risk:entry-risk,tp2=dir==="LONG"?entry+risk*1.5:entry-risk*1.5,tp3=dir==="LONG"?entry+risk*2:entry-risk*2,target=tp2;const rr=1.5;if(rr<MIN_RR)return{market:snapshot(pair,candles4h,dir,tl,price),debug:[...debug,"R:R below minimum"]};
 const l=liq(entry,dir),safe=dir==="LONG"?l*(1+LIQ_BUFFER):l*(1-LIQ_BUFFER);const daily513=getDaily513Diagnostic(candles4h);const agreesWith1D=(dir==="LONG"&&daily513.direction==="BULLISH")||(dir==="SHORT"&&daily513.direction==="BEARISH");const riskMultiplier=agreesWith1D?1:0.5;const baseRisk=risk;const positionSize=baseRisk*riskMultiplier;const trendAlignment=agreesWith1D?"WITH_1D":"AGAINST_1D";
 const breakoutRecord:BreakoutRecord=lastBreakout&&type!=="ENTRY_1"?lastBreakout:{direction:dir,price:round(tl.price),timestamp:now,candleIndex:i};
 const s:Signal={id:`${pair}_${type}_${now}`,pair,direction:dir,type,scale:type,entry:round(entry),stop:round(stop),target:round(target),tp1:round(tp1),tp2:round(tp2),tp3:round(tp3),confidence:type==="ENTRY_1"?80:type==="ENTRY_2"?70:85,rr,adx:a,rsi:r,stochK:st.k,stochD:st.d,expectedMove:Math.round(Math.abs(tp3-entry)/entry*1000)/10,reason:`${dir} ${type} | 4H trendline breakout/retest | 1D ${contextDir?strength(d,contextDir):"NEUTRAL"} | Stoch ${st.k}/${st.d}`,timestamp:now,version:CURRENT_SIGNAL_VERSION,trend:`${dir} ${strength(d,dir)}`,location:breakout?"BREAKOUT":"RETEST",trigger:"FIRED",context:{marketPhase:`${dir} ${strength(d,dir)}`,structure:breakout?"4H TRENDLINE BREAKOUT":"4H BREAKOUT RETEST",momentum:`RSI ${r} | Stoch ${st.k}/${st.d}`,pullback:retest?"confirmed_retest":"breakout",fourH513:get4HEmaDiagnostic(candles4h),daily513,trendAlignment,sizeMultiplier:riskMultiplier,risk:{baseRisk:round(baseRisk),positionSize:round(positionSize),trendAlignment,sizeMultiplier,riskMultiplier,estimatedLiquidation:round(l),safeBoundary:round(safe),leverage:LEVERAGE},breakoutRecord:{direction:breakoutRecord.direction,price:round(breakoutRecord.price),timestamp:breakoutRecord.timestamp,candleIndex:breakoutRecord.candleIndex},stages:{tp1:round(tp1),tp2:round(tp2),tp3:round(tp3),tp1R:1,tp2R:1.5,tp3R:2}}};
 debug.push(`SIGNAL: ${type} ${dir} @ ${s.entry} | SL ${s.stop} | TP1 ${s.tp1} | TP2 ${s.tp2} | TP3 ${s.tp3} | ${trendAlignment} | size x${riskMultiplier}`);return{signal:s,signals:[s],market:snapshot(pair,candles4h,dir,tl,price),debug};
}
export function getMarketSnapshot(pair:string,candles1h:Candle[],candles4h:Candle[],candles15m:Candle[]){const d=daily(candles4h),dir=bias(d),price=candles4h.at(-1)?.close||0;if(!dir)return{pair,price,timestamp:Date.now(),trend:"FLAT",location:"NONE",trigger:"NO_BIAS",adx:0,rsi:0,stochK:0,stochD:0,trendlinePrice:0,distToTrendline:null,momentumState:"NEUTRAL"};return snapshot(pair,candles4h,dir,trendline(candles4h,dir),price);}
export interface ValidityCheck{valid:boolean;reason:string;exited:boolean;state?:"VALID"|"STALE"|"INVALID";}
export function isSignalStillValid(s:Signal,p:number,now=Date.now()):ValidityCheck{if(now-s.timestamp>(s.type==="ADD"?4:24)*60*60*1000)return{valid:false,reason:"expired_ttl",exited:true,state:"STALE"};if(s.direction==="LONG"&&p<=s.stop)return{valid:false,reason:"sl_hit",exited:true,state:"INVALID"};if(s.direction==="SHORT"&&p>=s.stop)return{valid:false,reason:"sl_hit",exited:true,state:"INVALID"};const final=s.tp3??s.target;if(s.direction==="LONG"&&p>=final)return{valid:false,reason:"tp3_hit",exited:true,state:"STALE"};if(s.direction==="SHORT"&&p<=final)return{valid:false,reason:"tp3_hit",exited:true,state:"STALE"};return{valid:true,reason:"active",exited:false,state:"VALID"};}
export interface HoldResult{shouldHold:boolean;reason:string;newStop?:number;scaleOut?:{level:number;size:number;label:string};}
export function shouldHold(s:Signal,c:Candle[],p:number):HoldResult{const risk=Math.abs(s.entry-s.stop);if(risk){const r=s.direction==="LONG"?(p-s.entry)/risk:(s.entry-p)/risk;if(r>=2)return{shouldHold:false,reason:"tp3_hit",newStop:s.direction==="LONG"?s.entry+risk:s.entry-risk,scaleOut:{level:s.tp3??s.entry,size:.2,label:"TP3_FINAL"}};if(r>=1.5)return{shouldHold:true,reason:"tp2_hit_lock_1r_runner",newStop:s.direction==="LONG"?s.entry+risk:s.entry-risk,scaleOut:{level:s.tp2??s.entry,size:.4,label:"TP2"}};if(r>=1)return{shouldHold:true,reason:"tp1_hit_scale_out_40",newStop:s.entry,scaleOut:{level:s.tp1??s.entry,size:.4,label:"TP1"}};}return isSignalStillValid(s,p);}
export function shouldHoldCompat(s:Signal,c4:Candle[],c1:Candle[],p:number){return shouldHold(s,c4,p);}
export function filterExpiredSignals(signals:Signal[],prices:Record<string,number>,now?:number){const active:Signal[]=[],exited:{signal:Signal;reason:string}[]=[];for(const s of signals){const p=prices[s.pair];if(p===undefined){active.push(s);continue;}const v=isSignalStillValid(s,p,now);v.valid?active.push(s):exited.push({signal:s,reason:v.reason});}return{active,exited};}
export type TradeStatus="ACTIVE"|"TP_HIT"|"SL_HIT"|"EXPIRED";
export function checkTradeStatus(s:Signal,p:number,now=Date.now()):TradeStatus{const v=isSignalStillValid(s,p,now);if(v.reason==="expired_ttl")return"EXPIRED";if(s.direction==="LONG"&&p<=s.stop)return"SL_HIT";if(s.direction==="SHORT"&&p>=s.stop)return"SL_HIT";if(s.direction==="LONG"&&p>=(s.tp3??s.target))return"TP_HIT";if(s.direction==="SHORT"&&p<=(s.tp3??s.target))return"TP_HIT";return"ACTIVE";}
export function rebuildStateFromTrades(_:Record<string,any>):void{return;}
