import { NextResponse } from 'next/server';
const PAIRS:Record<string,string>={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'};const START=Date.parse('2026-07-31T00:00:00Z'),END=Date.parse('2026-09-10T00:00:00Z');
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const ema=(a:number[],p:number)=>{if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r};
const atr=(c:any[],p=14)=>avg(c.slice(-p).map((x:any,i:number)=>{const q=c[Math.max(0,c.length-p+i-1)]||x;return Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close))}));
const rsi=(a:number[],p=14)=>{if(a.length<2)return 50;let g=0,l=0,n=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d;n++}if(!n)return 50;if(!l)return 100;return 100-100/(1+(g/n)/(l/n))};
function stoch(a:number[]){const rv:number[]=[];for(let i=14;i<a.length;i++)rv.push(rsi(a.slice(i-14,i+1)));if(rv.length<14)return{k:50,d:50};const raw:number[]=[];for(let i=13;i<rv.length;i++){const w=rv.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100)}return{k:avg(raw.slice(-3)),d:avg(raw.slice(-5))}}
function daily(c:any[]){const m=new Map<string,any[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!m.has(k))m.set(k,[]);m.get(k)!.push(x)}return [...m.values()].map(b=>({timestamp:b[0].timestamp,open:b[0].open,high:Math.max(...b.map(x=>x.high)),low:Math.min(...b.map(x=>x.low)),close:b.at(-1).close,volume:b.reduce((s,x)=>s+x.volume,0)}))}
function bias(c:any[]){const d=daily(c);if(d.length<20)return null;const cl=d.map(x=>x.close),f=ema(cl,5).at(-1)!,s=ema(cl,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function pivots(c:any[],dir:string,w=2){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,wv=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...wv):v===Math.max(...wv))r.push({index:i,price:v})}return r}
function tl(c:any[],dir:string){const recent=pivots(c,dir,2).filter(x=>x.index>=c.length-60);if(recent.length<2)return null;const a=recent.at(-2),b=recent.at(-1),s=(b.price-a.price)/(b.index-a.index);if(dir==='LONG'&&s<=0||dir==='SHORT'&&s>=0)return null;const price=a.price+s*(c.length-1-a.index),buf=Math.max(price*.005,atr(c)*.35);for(let i=b.index+1;i<c.length;i++){const line=s*i+(price-s*(c.length-1));if(dir==='LONG'&&c[i].close<line-buf||dir==='SHORT'&&c[i].close>line+buf)return null}return{price,slope:s,anchor:b.index,candidates:recent.length,age:c.length-1-a.index}}
async function get(pair:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair]}&interval=240&since=${Math.floor((START-30*86400000)/1000)}`;const j=await(await fetch(u,{cache:'no-store'})).json(),k=Object.keys(j.result).find(x=>x!=='last')!;return j.result[k].map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:any)=>x.timestamp>=START&&x.timestamp<=END)}
function scan(c:any[]){const out:any={bars:c.length,bias:{LONG:0,SHORT:0},tlValid:0,noTL:0,near:0,notNear:0,extreme:0,notExtreme:0,nearExtreme:0,nearTurn:0,nearTurnNonExtreme:0,nearNonExtreme:0,nearExtremeAndTurn:0,distExtreme:[],examples:[]};for(let i=40;i<c.length;i++){const h=c.slice(0,i+1),d=bias(h);if(!d)continue;out.bias[d]++;const t=tl(h,d);if(!t){out.noTL++;continue}out.tlValid++;const p=h.at(-1).close,dist=(p-t.price)/t.price,near=Math.abs(dist)<.012,st=stoch(h.map(x=>x.close)),ext=d==='LONG'?st.k<20:st.k>80,turn=d==='LONG'?st.k>st.d:st.k<st.d;near?out.near++:out.notNear++;ext?out.extreme++:out.notExtreme++;if(ext)out.distExtreme.push(Math.abs(dist)*100);if(near&&ext){out.nearExtreme++;if(out.examples.length<30)out.examples.push({time:new Date(h.at(-1).timestamp).toISOString(),direction:d,price:+p.toFixed(4),tl:+t.price.toFixed(4),distPct:+(dist*100).toFixed(3),k:+st.k.toFixed(1),d:+st.d.toFixed(1),candidates:t.candidates,age:t.age})}if(near&&turn)out.nearTurn++;if(near&&turn&&!ext)out.nearTurnNonExtreme++;if(near&&!ext)out.nearNonExtreme++;if(near&&ext&&turn)out.nearExtremeAndTurn++}out.extremeDistance={min:out.distExtreme.length?+Math.min(...out.distExtreme).toFixed(3):null,median:out.distExtreme.length?+([...out.distExtreme].sort((a:number,b:number)=>a-b)[Math.floor(out.distExtreme.length/2)]).toFixed(3):null,avg:out.distExtreme.length?+avg(out.distExtreme).toFixed(3):null};delete out.distExtreme;return out}
export async function GET(){const out:any={period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},pairs:{}};for(const pair of Object.keys(PAIRS)){const c=await get(pair);out.pairs[pair]=scan(c)}return NextResponse.json(out)}
