const PAIRS={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'} as const;
const START=Date.parse('2026-05-13T00:00:00Z'), END=Date.parse('2026-09-10T00:00:00Z');
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function rsi(a:number[],p=14){if(a.length<p+1)return 50;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(!l)return 100;return 100-100/(1+(g/p)/(l/p))}
function macd(a:number[]){const e12=ema(a,12),e26=ema(a,26),m=a.map((_,i)=>e12[i]-e26[i]),s=ema(m,9);return{h:m.at(-1)!-s.at(-1)!}}
function dmi(c:C[],p=14){if(c.length<p+2)return{adx:0,plus:0,minus:0};const tr:number[]=[],pl:number[]=[],mi:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));const up=x.high-q.high,down=q.low-x.low;pl.push(up>down&&up>0?up:0);mi.push(down>up&&down>0?down:0)}const sm=(a:number[])=>{let z=avg(a.slice(0,p));const r=[z];for(let i=p;i<a.length;i++){z=(z*(p-1)+a[i])/p;r.push(z)}return r};const t=sm(tr),pd=sm(pl),md=sm(mi),dx:number[]=[],plus:number[]=[],minus:number[]=[];for(let i=0;i<t.length;i++){plus.push(pd[i]/t[i]*100);minus.push(md[i]/t[i]*100);const q=plus[i]+minus[i];dx.push(q?Math.abs(plus[i]-minus[i])/q*100:0)}return{adx:sm(dx).at(-1)!,plus:plus.at(-1)!,minus:minus.at(-1)!}}
function piv(c:C[],type:'H'|'L',w:number){const r:{i:number;p:number}[]=[];for(let i=w;i<c.length-w;i++){const v=type==='H'?c[i].high:c[i].low;if(c.slice(i-w,i+w+1).every((x,j)=>j===w||(type==='H'?x.high<=v:x.low>=v)))r.push({i:i+w,p:v})}return r}
function structure(c:C[],w:number){const H=piv(c,'H',w).slice(-2),L=piv(c,'L',w).slice(-2);if(H.length<2||L.length<2)return 'T';const hh=H[1].p>H[0].p,ll=L[1].p<L[0].p,hl=L[1].p>L[0].p,lh=H[1].p<H[0].p;return hh&&hl?'B':lh&&ll?'S':'T'}
function emaDir(c:C[]){const a=c.map(x=>x.close),e20=ema(a,20),e50=ema(a,50),e200=ema(a,200),p=a.at(-1)!;return e20.at(-1)!>e50.at(-1)!&&e50.at(-1)!>e200.at(-1)!&&p>e20.at(-1)!?'B':e20.at(-1)!<e50.at(-1)!&&e50.at(-1)!<e200.at(-1)!&&p<e20.at(-1)!?'S':'T'}
function five(c:C[]){const a=c.map(x=>x.close),e5=ema(a,5).at(-1)!,e13=ema(a,13).at(-1)!;return e5>e13?'B':e5<e13?'S':'T'}
function state(c:C[],model:string,w:number,persist:number){const d=emaDir(c),s=structure(c,w),f=five(c),a=c.map(x=>x.close),r=rsi(a),m=macd(a),dm=dmi(c);let raw='T';if(model==='STRUCT')raw=s;else if(model==='EMA_STRUCT')raw=d!=='T'&&s===d?d:'T';else if(model==='EMA_STRUCT_ADX')raw=d!=='T'&&s===d&&dm.adx>=20&&((d==='B'&&dm.plus>dm.minus)||(d==='S'&&dm.minus>dm.plus))?d:'T';else if(model==='EMA_STRUCT_MOM')raw=d!=='T'&&s===d&&((d==='B'&&r>50&&m.h>0)||(d==='S'&&r<50&&m.h<0))?d:'T';else if(model==='EMA_STRUCT_ADX_MOM')raw=d!=='T'&&s===d&&((d==='B'&&r>50&&m.h>0&&dm.adx>=20&&dm.plus>dm.minus)||(d==='S'&&r<50&&m.h<0&&dm.adx>=20&&dm.minus>dm.plus))?d:'T';else if(model==='5_13_STRUCT')raw=f!=='T'&&s===f?f:'T';else if(model==='5_13_EMA_STRUCT')raw=f!=='T'&&d===f&&s===f?f:'T';return raw}
async function get(pair:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair as keyof typeof PAIRS]}&interval=1440&since=${Math.floor((START-320*86400000)/1000)}`;const j=await(await fetch(u,{cache:'no-store'})).json();const k=Object.keys(j.result||{}).find(x=>x!=='last');return(j.result?.[k]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]} as C)).filter((x:C)=>x.timestamp<=END)}
const BASE=['EMA','STRUCT','EMA_STRUCT','EMA_STRUCT_ADX','EMA_STRUCT_MOM','EMA_STRUCT_ADX_MOM','5_13_STRUCT','5_13_EMA_STRUCT'];
const MODELS:string[]=[];for(const b of BASE)for(const p of [1,2,3])MODELS.push(`${b}_P${p}`);for(const w of [2,3,4])MODELS.push(`STRUCT_W${w}_P1`,`EMA_STRUCT_W${w}_P2`);
function calc(c:C[],model:string){const parts=model.split('_'),p=Number((parts.at(-1)||'P1').replace('P',''))||1,w=model.includes('W')?Number(parts.find(x=>x.startsWith('W'))!.replace('W','')):2,base=model.replace(/_P\d+$/,'').replace(/_W\d+/,'');const rows=c.map((_,i)=>i<210?'T':state(c.slice(0,i+1),base,w,p));const m:any={signals:0,bull:0,bear:0,transition:0,changes:0,flips:0,persist:p};let prev='T',last='T',streak=0;for(let i=210;i<c.length;i++){let q=rows[i];if(q===last)streak++;else streak=1;last=q;if(streak<p)q=prev;if(q!==prev){m.changes++;if(q!=='T'&&prev!=='T')m.flips++;}prev=q;if(q==='T'){m.transition++;continue}m.signals++;q==='B'?m.bull++:m.bear++;for(const n of [3,7,14])if(i+n<c.length){const rr=c[i+n].close/c[i].close-1;const al=rr*(q==='B'?1:-1);m[`ret${n}`]=(m[`ret${n}`]||0)+al;m[`hit${n}`]=(m[`hit${n}`]||0)+(al>0?1:0)}}for(const n of [3,7,14]){const den=Math.max(1,m.signals-n);m[`hitRate${n}`]=+(100*m[`hit${n}`]/den).toFixed(2);m[`avgAlignedReturn${n}`]=+(100*m[`ret${n}`]/den).toFixed(3)}return m}
(async()=>{const all:any={period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},models:MODELS,byPair:{}};for(const p of Object.keys(PAIRS)){all.byPair[p]={};const c=await get(p);for(const m of MODELS)all.byPair[p][m]=calc(c,m)}for(const m of MODELS){const a=Object.values(all.byPair).map((x:any)=>x[m]);const sum=(k:string)=>a.reduce((s:any,x:any)=>s+(x[k]||0),0);all[m]={signals:sum('signals'),bull:sum('bull'),bear:sum('bear'),transition:sum('transition'),changes:sum('changes'),flips:sum('flips'),hitRate3:+(100*sum('hit3')/Math.max(1,sum('signals')-4)).toFixed(2),hitRate7:+(100*sum('hit7')/Math.max(1,sum('signals')-4)).toFixed(2),hitRate14:+(100*sum('hit14')/Math.max(1,sum('signals')-4)).toFixed(2),avgAlignedReturn3:+(100*sum('ret3')/Math.max(1,sum('signals')-4)).toFixed(3),avgAlignedReturn7:+(100*sum('ret7')/Math.max(1,sum('signals')-4)).toFixed(3),avgAlignedReturn14:+(100*sum('ret14')/Math.max(1,sum('signals')-4)).toFixed(3)}}console.log('=== FULL 1D STRUCTURE MATRIX ===');console.log(JSON.stringify(all,null,2));console.log('=== END FULL 1D STRUCTURE MATRIX ===')})().catch(e=>{console.error(e);process.exit(1)})