const PAIRS={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'} as const;
const START=Date.parse('2026-05-13T00:00:00Z'), END=Date.parse('2026-09-10T00:00:00Z');
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function rsi(a:number[],p=14){if(a.length<p+1)return 50;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(l===0)return 100;const rs=(g/p)/(l/p);return 100-100/(1+rs)}
function macd(a:number[]){const e12=ema(a,12),e26=ema(a,26),m=a.map((_,i)=>e12[i]-e26[i]),s=ema(m,9);return{m:m.at(-1)!,s:s.at(-1)!,h:m.at(-1)!-s.at(-1)!,hp:m.at(-2)!-s.at(-2)!}}
function dmi(c:C[],p=14){if(c.length<p+2)return{adx:0,plus:0,minus:0};const tr:number[]=[],pl:number[]=[],mi:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));const up=x.high-q.high,down=q.low-x.low;pl.push(up>down&&up>0?up:0);mi.push(down>up&&down>0?down:0)}const sm=(a:number[])=>{let z=avg(a.slice(0,p));const r=[z];for(let i=p;i<a.length;i++){z=(z*(p-1)+a[i])/p;r.push(z)}return r};const t=sm(tr),pd=sm(pl),md=sm(mi),dx:number[]=[],plus:number[]=[],minus:number[]=[];for(let i=0;i<t.length;i++){plus.push(pd[i]/t[i]*100);minus.push(md[i]/t[i]*100);const q=plus[i]+minus[i];dx.push(q?Math.abs(plus[i]-minus[i])/q*100:0)}const ad=sm(dx);return{adx:ad.at(-1)!,plus:plus.at(-1)!,minus:minus.at(-1)!}}
function piv(c:C[],type:'H'|'L',w=2){const r:{i:number;p:number}[]=[];for(let i=w;i<c.length-w;i++){const v=type==='H'?c[i].high:c[i].low,ok=c.slice(i-w,i+w+1).every((x,j)=>j===w||(type==='H'?x.high<=v:x.low>=v));if(ok)r.push({i:i+w,p:v})}return r}
function structure(c:C[]){const H=piv(c,'H').slice(-2),L=piv(c,'L').slice(-2);if(H.length<2||L.length<2)return 'T';const bull=H[1].p>H[0].p&&L[1].p>L[0].p,bear=H[1].p<H[0].p&&L[1].p<L[0].p;return bull?'B':bear?'S':'T'}
function tl(c:C[],dir:'B'|'S'){const p=piv(c,dir==='B'?'L':'H').slice(-3);if(p.length<2)return null;const a=p.at(-2)!,b=p.at(-1)!,s=(b.p-a.p)/(b.i-a.i);if(dir==='B'&&s<=0||dir==='S'&&s>=0)return null;const line=s*(c.length-1)+(a.p-s*a.i),price=c.at(-1)!.close;return dir==='B'?price>=line?'B':'T':price<=line?'S':'T'}
function state(c:C[],name:string){const cl=c.map(x=>x.close),e5=ema(cl,5).at(-1)!,e13=ema(cl,13).at(-1)!,e20=ema(cl,20),e50=ema(cl,50),e200=ema(cl,200),p=cl.at(-1)!,b= e20.at(-1)!>e50.at(-1)!&&e50.at(-1)!>e200.at(-1)!,s=e20.at(-1)!<e50.at(-1)!&&e50.at(-1)!<e200.at(-1)!,slB=e20.at(-1)!>e20.at(-4)!&&e50.at(-1)!>e50.at(-4)!,slS=e20.at(-1)!<e20.at(-4)!&&e50.at(-1)!<e50.at(-4)!,r=rsi(cl),rp=rsi(cl.slice(0,-1)),mc=macd(cl),dm=dmi(c),st=structure(c),tb=tl(c,'B'),ts=tl(c,'S');
const emaDir=b&&p>e20.at(-1)!?'B':s&&p<e20.at(-1)!?'S':'T';
const emaSlope=emaDir==='B'&&slB?'B':emaDir==='S'&&slS?'S':'T';
const five=e5>e13?'B':e5<e13?'S':'T';
const ema5=emaDir!=='T'&&five===emaDir?emaDir:'T';
const rules:Record<string,string>= {
'EMA':emaDir,'EMA_SLOPE':emaSlope,'5_13':five,'EMA_5_13':ema5,
'EMA_STRUCTURE':emaDir!=='T'&&st===emaDir?emaDir:'T',
'EMA_TRENDLINE':emaDir!=='T'&&((emaDir==='B'&&tb==='B')||(emaDir==='S'&&ts==='S'))?emaDir:'T',
'EMA_STRUCTURE_TL':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&tb==='B')||(emaDir==='S'&&ts==='S'))?emaDir:'T',
'EMA_STRUCTURE_RSI':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&r>50&&r>=rp)||(emaDir==='S'&&r<50&&r<=rp))?emaDir:'T',
'EMA_STRUCTURE_MACD':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&mc.h>0&&mc.h>=mc.hp)||(emaDir==='S'&&mc.h<0&&mc.h<=mc.hp))?emaDir:'T',
'EMA_STRUCTURE_ADX':emaDir!=='T'&&st===emaDir&&dm.adx>=20&&((emaDir==='B'&&dm.plus>dm.minus)||(emaDir==='S'&&dm.minus>dm.plus))?emaDir:'T',
'EMA_STRUCTURE_MOMENTUM':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&r>50&&mc.h>0)||(emaDir==='S'&&r<50&&mc.h<0))?emaDir:'T',
'EMA_STRUCTURE_TL_ADX':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&tb==='B'&&dm.adx>=20&&dm.plus>dm.minus)||(emaDir==='S'&&ts==='S'&&dm.adx>=20&&dm.minus>dm.plus))?emaDir:'T',
'EMA_STRUCTURE_MOM_ADX':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&r>50&&mc.h>0&&dm.adx>=20&&dm.plus>dm.minus)||(emaDir==='S'&&r<50&&mc.h<0&&dm.adx>=20&&dm.minus>dm.plus))?emaDir:'T',
'FULL':emaDir!=='T'&&st===emaDir&&((emaDir==='B'&&tb==='B'&&r>50&&mc.h>0&&dm.adx>=20&&dm.plus>dm.minus)||(emaDir==='S'&&ts==='S'&&r<50&&mc.h<0&&dm.adx>=20&&dm.minus>dm.plus))?emaDir:'T'};
return rules[name]}
async function get(pair:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair as keyof typeof PAIRS]}&interval=1440&since=${Math.floor((START-320*86400000)/1000)}`;const j=await (await fetch(u,{cache:'no-store'})).json();const k=Object.keys(j.result||{}).find(x=>x!=='last');return(j.result?.[k]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]} as C)).filter((x:C)=>x.timestamp<=END)}
const MODELS=['EMA','EMA_SLOPE','5_13','EMA_5_13','EMA_STRUCTURE','EMA_TRENDLINE','EMA_STRUCTURE_TL','EMA_STRUCTURE_RSI','EMA_STRUCTURE_MACD','EMA_STRUCTURE_ADX','EMA_STRUCTURE_MOMENTUM','EMA_STRUCTURE_TL_ADX','EMA_STRUCTURE_MOM_ADX','FULL'];
async function runPair(pair:string){const c=await get(pair),out:any={};for(const model of MODELS){const rows=c.map((x,i)=>i>=210?state(c.slice(0,i+1),model):'T');const m:any={signals:0,bull:0,bear:0,transition:0,hits3:0,hits7:0,hits14:0,ret3:0,ret7:0,ret14:0,changes:0};let prev='T';for(let i=210;i<c.length;i++){const q=rows[i];if(q!==prev)m.changes++;prev=q;if(q==='T'){m.transition++;continue}m.signals++;if(q==='B')m.bull++;else m.bear++;for(const [n,d] of [[3,3],[7,7],[14,14]] as [number,number][])if(i+d<c.length){const rr=c[i+d].close/c[i].close-1;m[`ret${n}`]+=rr*(q==='B'?1:-1);if(rr*(q==='B'?1:-1)>0)m[`hits${n}`]++}}for(const n of [3,7,14]){m[`hitRate${n}`]=+(100*m[`hits${n}`]/Math.max(1,m.signals-(n))).toFixed(2);m[`avgAlignedReturn${n}`]=+(100*m[`ret${n}`]/Math.max(1,m.signals-(n))).toFixed(3)}out[model]=m}return out}
(async()=>{const all:any={period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},models:MODELS,byPair:{}};for(const p of Object.keys(PAIRS)){console.log(`RUN ${p}`);all.byPair[p]=await runPair(p)}for(const model of MODELS){const a=Object.values(all.byPair).map((x:any)=>x[model]);const sum=(k:string)=>a.reduce((s:any,x:any)=>s+x[k],0);all[model]={pairs:4,signals:sum('signals'),bull:sum('bull'),bear:sum('bear'),transition:sum('transition'),changes:sum('changes'),hitRate3:+(100*sum('hits3')/Math.max(1,sum('signals')-4)).toFixed(2),hitRate7:+(100*sum('hits7')/Math.max(1,sum('signals')-4)).toFixed(2),hitRate14:+(100*sum('hits14')/Math.max(1,sum('signals')-4)).toFixed(2),avgAlignedReturn3:+(100*sum('ret3')/Math.max(1,sum('signals')-4)).toFixed(3),avgAlignedReturn7:+(100*sum('ret7')/Math.max(1,sum('signals')-4)).toFixed(3),avgAlignedReturn14:+(100*sum('ret14')/Math.max(1,sum('signals')-4)).toFixed(3)}}console.log('=== 1D DIRECTION COMBINATION BACKTEST ===');console.log(JSON.stringify(all,null,2));console.log('=== END 1D DIRECTION COMBINATION BACKTEST ===')})().catch(e=>{console.error(e);process.exit(1)})
