import { NextResponse } from 'next/server';
const PAIRS:Record<string,string>={BTC:'PF_XBTUSD',ETH:'PF_ETHUSD',SOL:'PF_SOLUSD',HYPE:'PF_HYPEUSD'};
const START=Date.parse('2026-03-13T00:00:00Z'),END=Date.parse('2026-09-13T00:00:00Z');
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){if(c.length<2)return 0;const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(r)}
function piv(c:C[],dir:'LONG'|'SHORT',w:number){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,vs=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...vs):v===Math.max(...vs))r.push({i,p:v})}return r}
function lineFrom(c:C[],dir:'LONG'|'SHORT',w:number,look:number){const p=piv(c,dir,w).filter(x=>x.i>=Math.max(0,c.length-look));if(p.length<2)return null;const a=p.at(-2),b=p.at(-1);const slope=(b.p-a.p)/(b.i-a.i);if(dir==='LONG'&&slope<=0)return null;if(dir==='SHORT'&&slope>=0)return null;return{id:`${dir}-${a.i}-${b.i}`,a:a.i,b:b.i,slope,intercept:a.p-slope*a.i,price:(i:number)=>slope*i+(a.p-slope*a.i)}}
function bias(c:C[]){const d=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!d.has(k))d.set(k,[]);d.get(k)!.push(x)}const a=[...d.values()].map(x=>x.at(-1)!.close);if(a.length<20)return null;const f=ema(a,5).at(-1)!,s=ema(a,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function stoch(c:C[]){const a=c.map(x=>x.close),rs:number[]=[];function rsi(z:number[],p=14){let g=0,l=0;for(let i=Math.max(1,z.length-p);i<z.length;i++){const q=z[i]-z[i-1];if(q>0)g+=q;else l-=q}const n=Math.min(p,z.length-1);if(!n)return 50;g/=n;l/=n;return l===0?100:100-100/(1+g/l)}for(let i=14;i<a.length;i++)rs.push(rsi(a.slice(i-14,i+1)));if(rs.length<14)return{k:50,d:50};const raw:number[]=[];for(let i=13;i<rs.length;i++){const q=rs.slice(i-13,i+1),lo=Math.min(...q),hi=Math.max(...q);raw.push(hi===lo?50:(rs[i]-lo)/(hi-lo)*100)}return{k:raw.at(-1)??50,d:avg(raw.slice(-3))}}
function result(){return{trades:0,wins:0,losses:0,r:0,signals:0,e1:0,e2:0}}
function run(c:C[],mode:'touch'|'reject'|'br3'|'br6'|'br12'|'atrTouch',w=2,look=60){let tr:any=null,line:any=null,broken:any=null,lastLine='';const o=result();for(let i=120;i<c.length;i++){const h=c.slice(0,i+1),x=c[i];if(tr){const win=tr.dir==='LONG'?x.high>=tr.tp:x.low<=tr.tp,loss=tr.dir==='LONG'?x.low<=tr.stop:x.high>=tr.stop;if(win){o.trades++;o.wins++;o.r+=2;tr=null;continue}if(loss){o.trades++;o.losses++;o.r-=1;tr=null;continue}}
for(const dir of ['LONG','SHORT'] as const){const t=lineFrom(h,dir,w,look);if(!t)continue;if(t.id!==lastLine){line=t;lastLine=t.id;broken=null}if(line?.id===t.id){const lp=line.price(i),a=atr(h),buf=mode==='atrTouch'?a*.35:lp*.012;const cross=dir==='LONG'?x.close<lp-Math.max(lp*.005,a*.35):x.close>lp+Math.max(lp*.005,a*.35);if(cross){line=null;broken=null;lastLine='';continue}if(broken&&broken.dir===dir){const retest=dir==='LONG'?x.low<=broken.lp+buf&&x.high>=broken.lp-buf:x.high>=broken.lp-buf&&x.low<=broken.lp+buf;const confirm=dir==='LONG'?x.close>x.open&&x.close>lp:x.close<x.open&&x.close<lp;if(retest&&confirm&&i>broken.bi){const entry=x.close,risk=Math.max(a*2,entry*.015);tr={dir,entry,stop:dir==='LONG'?entry-risk:entry+risk,tp:dir==='LONG'?entry+risk*2:entry-risk*2};o.signals++;mode==='br3'||mode==='br6'||mode==='br12'?o.e2++:o.e1++;broken=null;break}}
if(!broken){const br=dir==='LONG'?x.close>lp&&c[i-1].close<=line.price(i-1):x.close<lp&&c[i-1].close>=line.price(i-1);if(br&&mode.startsWith('br')){broken={dir,lp,bi:i};continue}}
if(!tr&&(mode==='touch'||mode==='reject'||mode==='atrTouch')){const near=Math.abs(x.close-lp)/lp<(mode==='atrTouch'?Math.max(.004,buf/lp):.012);const touch=dir==='LONG'?x.low<=lp+buf&&x.high>=lp-buf:x.high>=lp-buf&&x.low<=lp+buf;const reject=dir==='LONG'?x.close>x.open&&x.close>lp:x.close<x.open&&x.close<lp;const s=stoch(h),turn=dir==='LONG'?s.k>s.d:s.k<s.d,ext=dir==='LONG'?s.k<20:s.k>80;const ok=mode==='touch'?near&&(ext||turn):touch&&reject&&(ext||turn);if(ok&&bias(h)===dir){const entry=x.close,risk=Math.max(a*2,entry*.015);tr={dir,entry,stop:dir==='LONG'?entry-risk:entry+risk,tp:dir==='LONG'?entry+risk*2:entry-risk*2};o.signals++;ext?o.e1++:o.e2++;break}}}}
}
if(tr){const p=c.at(-1)!.close,r=(tr.dir==='LONG'?p-tr.entry:tr.entry-p)/Math.abs(tr.entry-tr.stop);o.trades++;r>0?o.wins++:o.losses++;o.r+=r}return o}
async function fetchPair(pair:string){const u=`https://futures.kraken.com/api/charts/v1/trade/${PAIRS[pair]}/4h?from=${Math.floor((START-45*86400000)/1000)}&to=${Math.floor(END/1000)}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`${pair} ${r.status}`);const d=await r.json();return(d.candles||[]).map((x:any)=>({timestamp:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume})).filter((x:C)=>x.timestamp>=START&&x.timestamp<=END)}
export async function GET(){const modes=['touch','reject','atrTouch','br3','br6','br12'] as const;const out:any={period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},note:'Research only; persistent point-to-point TL lifecycle. No production strategy changes.',summary:{},byAsset:{}};for(const p of Object.keys(PAIRS)){const c=await fetchPair(p);out.byAsset[p]={candles:c.length};for(const m of modes){const z=run(c,m);out.byAsset[p][m]=z} }for(const m of modes){let z=result();for(const p of Object.keys(PAIRS)){const a=out.byAsset[p][m];for(const k of Object.keys(z) as (keyof typeof z)[])z[k]+=a[k]}out.summary[m]={...z,winRate:z.trades?100*z.wins/z.trades:0,pf:z.losses?z.wins*2/z.losses:0}}return NextResponse.json(out)}