import { NextResponse } from 'next/server'

const PAIRS={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'} as const
const START=Date.parse('2026-07-31T00:00:00Z'),END=Date.parse('2026-09-10T00:00:00Z')
type C={timestamp:number,open:number,high:number,low:number,close:number,volume:number}; type D='LONG'|'SHORT'
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0
const ema=(a:number[],p:number)=>{if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
const atr=(c:C[],p=14)=>avg(c.slice(-p).map((x,i)=>{const q=c[Math.max(0,c.length-p+i-1)]||x;return Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close))}))
const rsi=(a:number[],p=14)=>{if(a.length<2)return 50;let g=0,l=0,n=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d;n++}if(!n)return 50;if(!l)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
function stoch(a:number[]){const rv:number[]=[];for(let i=14;i<a.length;i++)rv.push(rsi(a.slice(i-14,i+1)));if(rv.length<14)return{k:50,d:50};const raw:number[]=[];for(let i=13;i<rv.length;i++){const w=rv.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100)}return{k:avg(raw.slice(-3)),d:avg(raw.slice(-5))}}
function daily(c:C[]){const m=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!m.has(k))m.set(k,[]);m.get(k)!.push(x)}return [...m.values()].map(b=>({timestamp:b[0].timestamp,open:b[0].open,high:Math.max(...b.map(x=>x.high)),low:Math.min(...b.map(x=>x.low)),close:b.at(-1)!.close,volume:b.reduce((s,x)=>s+x.volume,0)}))}
function bias(c:C[]):D|null{const d=daily(c);if(d.length<20)return null;const cl=d.map(x=>x.close),f=ema(cl,5).at(-1)!,s=ema(cl,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function pivots(c:C[],dir:D,w=2){const r:{index:number,price:number}[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,wv=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...wv):v===Math.max(...wv))r.push({index:i,price:v})}return r}
function pt(p:{index:number,price:number}[],c:C[],dir:D){if(p.length<2)return null;const a=p.at(-2)!,b=p.at(-1)!,s=(b.price-a.price)/(b.index-a.index);if(dir==='LONG'&&s<=0||dir==='SHORT'&&s>=0)return null;return{price:a.price+s*(c.length-1-a.index),slope:s,anchor:b.index}}
function tl(c:C[],dir:D){const recent=pivots(c,dir,2).filter(x=>x.index>=c.length-60);if(recent.length<2)return null;const q=pt(recent.slice(-5),c,dir);if(!q)return null;const buf=Math.max(q.price*.005,atr(c)*.35);for(let i=q.anchor+1;i<c.length;i++){const line=q.slope*i+(q.price-q.slope*(c.length-1));if(dir==='LONG'&&c[i].close<line-buf||dir==='SHORT'&&c[i].close>line+buf)return null}return q}
function conditions(c:C[],dir:D){const t=tl(c,dir);if(!t)return null;const p=c.at(-1)!.close,near=Math.abs((p-t.price)/t.price)<.012,beyond=dir==='LONG'?p>t.price*1.008:p<t.price*.992,cl=c.map(x=>x.close),e8=ema(cl,8).at(-1)!,e21=ema(cl,21).at(-1)!,aligned=dir==='LONG'?p>e8&&p>e21:p<e8&&p<e21,s=stoch(cl),turn=dir==='LONG'?s.k>s.d:s.k<s.d,ext=dir==='LONG'?s.k<20:s.k>80,confirm=dir==='LONG'?p>c.at(-1)!.open:p<c.at(-1)!.open,vol=c.at(-1)!.volume>avg(c.slice(-10).map(x=>x.volume))*1.3;let raw:'ENTRY_1'|'ENTRY_2'|'ADD'|null=near&&ext?'ENTRY_1':near&&turn&&!ext?'ENTRY_2':beyond&&confirm&&aligned&&(vol||turn)?'ADD':null;return{t,p,raw,dir,stoch:s}}
async function get(pair:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair as keyof typeof PAIRS]}&interval=240&since=${Math.floor((START-30*86400000)/1000)}`;const j=await(await fetch(u)).json();const k=Object.keys(j.result).find(x=>x!=='last')!;return j.result[k].map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:C)=>x.timestamp>=START&&x.timestamp<=END) as C[]}
function initial(c:C[],d:D){const s=conditions(c,d);if(!s||s.raw!=='ENTRY_1')return null;const a=atr(c),entry=s.p,lo=Math.min(...c.slice(-10).map(x=>x.low)),hi=Math.max(...c.slice(-10).map(x=>x.high)),structural=d==='LONG'?Math.min(lo,entry-a*2):Math.max(hi,entry+a*2),stop=d==='LONG'?Math.max(Math.min(structural,entry*.992),entry*.965):Math.min(Math.max(structural,entry*1.008),entry*1.035),risk=Math.abs(entry-stop);return risk?{entry,stop,risk,tp1:d==='LONG'?entry+risk:entry-risk,tp15:d==='LONG'?entry+1.5*risk:entry-1.5*risk,tp2:d==='LONG'?entry+2*risk:entry-2*risk}:null}
function run(c:C[]){const out:any={entry1Opportunities:[],progressed:0,entry2:0,add:0,entry2AfterEntry1:0,addAfterEntry1:0,entry2ThenAdd:0,closedAtR15:{trades:0,wins:0,losses:0,netR:0,r15:0,slBeforeR15:0},allTradesAtR2:{trades:0,wins:0,losses:0,netR:0,r2:0}};let pos:any=null;for(let i=40;i<c.length;i++){const x=c[i];if(pos){const sign=pos.d==='LONG'?1:-1;const cond=conditions(c.slice(0,i+1),pos.d);if(cond?.raw==='ENTRY_2'&&!pos.entry2){pos.entry2=true;pos.entry2Ts=x.timestamp;out.entry2AfterEntry1++;out.entry2++}if(cond?.raw==='ADD'&&!pos.add){pos.add=true;pos.addTs=x.timestamp;out.addAfterEntry1++;out.add++}const hitSL=sign>0?x.low<=pos.stop:x.high>=pos.stop;const hit15=!pos.hit15&&(sign>0?x.high>=pos.tp15:x.low<=pos.tp15);const hit2=!pos.hit2&&(sign>0?x.high>=pos.tp2:x.low<=pos.tp2);if(hitSL){out.closedAtR15.trades++;out.allTradesAtR2.trades++;if(pos.hit15){out.closedAtR15.wins++;out.closedAtR15.netR+=0}else{out.closedAtR15.losses++;out.closedAtR15.netR-=1;out.closedAtR15.slBeforeR15++}if(pos.hit2){out.allTradesAtR2.wins++;out.allTradesAtR2.netR+=2}else if(pos.hit15){out.allTradesAtR2.wins++;out.allTradesAtR2.netR+=1.5}else{out.allTradesAtR2.losses++;out.allTradesAtR2.netR-=1}out.entry1Opportunities.push({...pos,closed:x.timestamp,outcome:'SL'});pos=null}else if(hit2){pos.hit2=true;out.closedAtR15.trades++;out.closedAtR15.wins++;out.closedAtR15.netR+=1.5;out.closedAtR15.r15++;out.allTradesAtR2.trades++;out.allTradesAtR2.wins++;out.allTradesAtR2.netR+=2;out.allTradesAtR2.r2++;out.entry1Opportunities.push({...pos,closed:x.timestamp,outcome:'R2'});pos=null}else if(hit15){pos.hit15=true;out.closedAtR15.trades++;out.closedAtR15.wins++;out.closedAtR15.netR+=1.5;out.closedAtR15.r15++;pos.stop=pos.entry}continue}const d=bias(c.slice(0,i+1));if(!d)continue;const s=initial(c.slice(0,i+1),d);if(s)pos={...s,d,ts:x.timestamp,entry2:false,add:false,hit15:false,hit2:false}}if(pos){const x=c.at(-1)!,sign=pos.d==='LONG'?1:-1,p=(x.close-pos.entry)*sign/pos.risk;out.entry1Opportunities.push({...pos,closed:x.timestamp,outcome:'OPEN',finalR:+p.toFixed(3)});if(p>=1.5){out.closedAtR15.trades++;out.closedAtR15.wins++;out.closedAtR15.netR+=1.5}else{out.closedAtR15.trades++;out.closedAtR15.netR+=p;p>=0?out.closedAtR15.wins++:out.closedAtR15.losses++}}out.progressed=out.entry1Opportunities.filter((x:any)=>x.entry2).length;out.entry2ThenAdd=out.entry1Opportunities.filter((x:any)=>x.entry2&&x.add).length;return out}
export async function GET(){const all:any={};for(const p of Object.keys(PAIRS)){const c=await get(p);all[p]=run(c)}console.log('[BACKTEST PROGRESSION]',JSON.stringify({period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},pairs:all}));return NextResponse.json({period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},pairs:all})}
