import { NextResponse } from 'next/server';

const PAIRS: Record<string,string>={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'};
const START=Date.parse('2026-07-31T00:00:00Z');
const END=Date.parse('2026-09-10T00:00:00Z');
const TL_THRESHOLD=.012;
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number};
type T={entry:number;stop:number;tp1:number;tp2:number;tp3:number;dir:'LONG'|'SHORT';openTs:number};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){if(!a.length)return[];const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){const r:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];r.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(r)}
function rsi(a:number[],p=14){if(a.length<2)return 50;let g=0,l=0,n=0;for(let i=Math.max(1,a.length-p);i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l+=-d;n++}if(!n)return 50;const ag=g/n,al=l/n;if(al===0)return 100;return 100-100/(1+ag/al)}
function rsiSeries(a:number[],p=14){const r:number[]=[];for(let i=p;i<a.length;i++)r.push(rsi(a.slice(i-p,i+1),p));return r}
function stoch(a:number[]){const rv=rsiSeries(a,14);if(rv.length<17)return{k:50,d:50};const raw:number[]=[];for(let i=13;i<rv.length;i++){const w=rv.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(rv[i]-lo)/(hi-lo)*100)}const kv:number[]=[];for(let i=2;i<raw.length;i++)kv.push(avg(raw.slice(i-2,i+1)));return kv.length<3?{k:50,d:50}:{k:kv.at(-1)!,d:avg(kv.slice(-3))}}
function wilder(a:number[],p:number){if(!a.length)return[];const r=[avg(a.slice(0,p))];for(let i=p;i<a.length;i++)r.push((r.at(-1)!*(p-1)+a[i])/p);return r}
function adx(c:C[],p=14){if(c.length<p+1)return 0;const tr:number[]=[],pl:number[]=[],mi:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));pl.push(x.high-q.high>q.low-x.low?Math.max(x.high-q.high,0):0);mi.push(q.low-x.low>x.high-q.high?Math.max(q.low-x.low,0):0)}const t=wilder(tr,p),pd=wilder(pl,p),md=wilder(mi,p),dx:number[]=[];for(let i=0;i<t.length;i++){const a=pd[i]/t[i]*100,b=md[i]/t[i]*100;dx.push(a+b===0?0:Math.abs(a-b)/(a+b)*100)}return wilder(dx,p).at(-1)||0}
function daily(c:C[]){const m=new Map<string,C[]>();for(const x of c){const k=new Date(x.timestamp).toISOString().slice(0,10);if(!m.has(k))m.set(k,[]);m.get(k)!.push(x)}return [...m.values()].map(b=>({timestamp:b[0].timestamp,open:b[0].open,high:Math.max(...b.map(x=>x.high)),low:Math.min(...b.map(x=>x.low)),close:b.at(-1)!.close,volume:b.reduce((s,x)=>s+x.volume,0)}))}
function bias(c:C[]){const d=daily(c);if(d.length<20)return null;const a=d.map(x=>x.close),f=ema(a,5).at(-1)!,s=ema(a,13).at(-1)!;return f>s?'LONG':f<s?'SHORT':null}
function pivots(c:C[],dir:'LONG'|'SHORT',w:number){const r:any[]=[];for(let i=w;i<c.length-w;i++){const v=dir==='LONG'?c[i].low:c[i].high,vals=c.slice(i-w,i+w+1).map(x=>dir==='LONG'?x.low:x.high);if(dir==='LONG'?v===Math.min(...vals):v===Math.max(...vals))r.push({index:i,price:v})}return r}
function regression(p:any[],c:C[],dir:any){if(p.length<3)return null;const n=p.length,sx=p.reduce((s,x)=>s+x.index,0),sy=p.reduce((s,x)=>s+x.price,0),sxy=p.reduce((s,x)=>s+x.index*x.price,0),sx2=p.reduce((s,x)=>s+x.index*x.index,0),den=n*sx2-sx*sx;if(!den)return null;const slope=(n*sxy-sx*sy)/den;if((dir==='LONG'&&slope<=0)||(dir==='SHORT'&&slope>=0))return null;const inter=(sy-slope*sx)/n;return {price:slope*(c.length-1)+inter,slope,anchor:p.at(-1).index}}
function point(p:any[],c:C[],dir:any){if(p.length<2)return null;const a=p.at(-2),b=p.at(-1),dx=b.index-a.index;if(dx<=0)return null;const slope=(b.price-a.price)/dx;if((dir==='LONG'&&slope<=0)||(dir==='SHORT'&&slope>=0))return null;return {price:slope*(c.length-1)+(a.price-slope*a.index),slope,anchor:b.index}}
function structured5(p:any[],dir:any){let out:any[]=[];for(const x of p){if(!out.length){out.push(x);continue}const last=out.at(-1);if(dir==='LONG'?x.price>last.price:x.price<last.price)out.push(x)}return out.slice(-5)}
function tl(c:C[],dir:any,variant:number){const w=variant===5?5:2,all=pivots(c,dir,w),look=variant===5?120:60,recent=all.filter(x=>x.index>=Math.max(0,c.length-look));if(recent.length<(variant===4?2:3))return null;let p=variant===5?structured5(recent,dir):recent.slice(-5);if(p.length<(variant===4?2:3))return null;const latest=p.at(-1).index;p=p.filter(x=>x.index>=latest-(variant===5?120:72));const q=variant===4?point(p,c,dir):regression(p,c,dir);if(!q)return null;const buffer=Math.max(q.price*.005,atr(c)*.35);for(let i=q.anchor+1;i<c.length;i++){const line=q.slope*i+(q.price-q.slope*(c.length-1));if(dir==='LONG'&&c[i].close<line-buffer)return null;if(dir==='SHORT'&&c[i].close>line+buffer)return null}return {...q,pivots:p}}
function structure(c:C[],dir:any){const hs=pivots(c,'SHORT',2),ls=pivots(c,'LONG',2);if(hs.length<2||ls.length<2)return false;const h1=hs.at(-1).price,h0=hs.at(-2).price,l1=ls.at(-1).price,l0=ls.at(-2).price;return dir==='LONG'?h1>h0&&l1>l0:h1<h0&&l1<l0}
function fourH513(c:C[],dir:any){const cl=c.map(x=>x.close),f=ema(cl,5).at(-1)!,s=ema(cl,13).at(-1)!;return dir==='LONG'?f>s:f<s}
function signal(c:C[],dir:any,variant:number){const t=tl(c,dir,variant);if(!t)return null;const price=c.at(-1)!.close,near=Math.abs((price-t.price)/t.price)<TL_THRESHOLD,beyond=dir==='LONG'?price>t.price*1.008:price<t.price*.992,cl=c.map(x=>x.close),e8=ema(cl,8).at(-1)!,e21=ema(cl,21).at(-1)!,aligned=dir==='LONG'?price>e8&&price>e21:price<e8&&price<e21,st=stoch(cl),turn=dir==='LONG'?st.k>st.d:st.k<st.d,extreme=dir==='LONG'?st.k<20:st.k>80,confirm=dir==='LONG'?price>c.at(-1)!.open:price<c.at(-1)!.open,vol=c.at(-1)!.volume>avg(c.slice(-10).map(x=>x.volume))*1.3,mom=turn,adxv=adx(c);let raw=near&&extreme?'ENTRY_1':near&&turn&&!extreme?'ENTRY_2':beyond&&confirm&&aligned&&(vol||mom||adxv>20)?'ADD':null;if(!raw)return null;if(variant===2&&!fourH513(c,dir))return null;if(variant===3&&(!fourH513(c,dir)||!structure(c,dir)))return null;const entry=price,atrv=atr(c),isAdd=raw==='ADD',lows=c.slice(-10).map(x=>x.low),highs=c.slice(-10).map(x=>x.high);const structural=dir==='LONG'?Math.min(Math.min(...lows),entry-atrv*(isAdd?1.25:2)):Math.max(Math.max(...highs),entry+atrv*(isAdd?1.25:2));let stop;if(dir==='LONG'){const minStop=entry*.965,maxStop=entry*.992;stop=Math.max(Math.min(structural,maxStop),minStop)}else{const minStop=entry*1.008,maxStop=entry*1.035;stop=Math.min(Math.max(structural,minStop),maxStop)}const risk=Math.abs(entry-stop);return risk?{dir,entry,stop,tp1:dir==='LONG'?entry+risk:entry-risk,tp2:dir==='LONG'?entry+risk*1.5:entry-risk*1.5,tp3:dir==='LONG'?entry+risk*2:entry-risk*2}:null}
async function fetchPair(pair:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${PAIRS[pair]}&interval=240&since=${Math.floor(START/1000)-30*86400}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${pair} HTTP ${r.status}`);const d=await r.json();const key=Object.keys(d.result||{}).find(k=>k!=='last');return (d.result?.[key]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:C)=>x.timestamp>=START&&x.timestamp<=END)}
function run(c:C[],pair:string,variant:number){let tr:T|null=null;const o:any={trades:0,wins:0,losses:0,net:0,gp:0,gl:0,r1:0,r15:0,r2:0,slBeforeR1:0,durations:[]};for(let i=40;i<c.length;i++){const hist=c.slice(0,i+1);if(tr){const x=c[i],r=Math.abs(tr.entry-tr.stop);const r1=tr.dir==='LONG'?x.high>=tr.tp1:x.low<=tr.tp1,r15=tr.dir==='LONG'?x.high>=tr.tp2:x.low<=tr.tp2,r2=tr.dir==='LONG'?x.high>=tr.tp3:x.low<=tr.tp3,sl=tr.dir==='LONG'?x.low<=tr.stop:x.high>=tr.stop;if(r1)o.r1++;if(r15)o.r15++;if(r2)o.r2++;if(sl){const pnl=tr.dir==='LONG'?tr.stop-tr.entry:tr.entry-tr.stop;o.trades++;o.losses++;o.net+=pnl;o.gl+=-pnl;o.durations.push((x.timestamp-tr.openTs)/3600000);if(!r1)o.slBeforeR1++;tr=null;continue}if(r2){const pnl=tr.dir==='LONG'?tr.tp3-tr.entry:tr.entry-tr.tp3;o.trades++;o.wins++;o.net+=pnl;o.gp+=pnl;o.durations.push((x.timestamp-tr.openTs)/3600000);tr=null;continue}}
if(!tr){const dir=bias(hist);if(dir){const s=signal(hist,dir,variant);if(s)tr={...s,openTs:c[i].timestamp}}}}
if(tr){const last=c.at(-1)!,pnl=tr.dir==='LONG'?last.close-tr.entry:tr.entry-last.close;o.trades++;if(pnl>=0){o.wins++;o.gp+=pnl}else{o.losses++;o.gl+=-pnl}o.net+=pnl;o.durations.push((last.timestamp-tr.openTs)/3600000)}return o}
export async function GET(){const byPair:any={},summary:any={};for(const pair of Object.keys(PAIRS)){const c=await fetchPair(pair);byPair[pair]={candles:c.length,variants:{}};for(let v=1;v<=5;v++)byPair[pair].variants[v]=run(c,pair,v)}for(let v=1;v<=5;v++){const a:any={trades:0,wins:0,losses:0,net:0,gp:0,gl:0,r1:0,r15:0,r2:0,slBeforeR1:0,durations:[]};for(const p of Object.keys(byPair)){const x=byPair[p].variants[v];for(const k of ['trades','wins','losses','net','gp','gl','r1','r15','r2','slBeforeR1'])a[k]+=x[k];a.durations.push(...x.durations)}summary[v]={trades:a.trades,wins:a.wins,losses:a.losses,winRate:a.trades?100*a.wins/a.trades:0,net:a.net,grossProfit:a.gp,grossLoss:a.gl,profitFactor:a.gl?a.gp/a.gl:0,avgTrade:a.trades?a.net/a.trades:0,avgDurationHours:a.durations.length?avg(a.durations):0,slBeforeR1Pct:a.losses?100*a.slBeforeR1/a.losses:0,r1HitEvents:a.r1,r15HitEvents:a.r15,r2HitEvents:a.r2}}
return NextResponse.json({period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},note:'Research backtest. Five variants use identical OHLC, entry/stop/target framework; variant 4 is exact point-to-point TL logic from commit 9df5dd8; variant 5 is the ±5 structured-pivot system concept from the V31 pivot architecture.',summary,byPair})}
