import {NextResponse} from 'next/server';
const P:any={BTC:'XBTUSD',ETH:'ETHUSD',SOL:'SOLUSD',HYPE:'HYPEUSD'},START=Date.parse('2026-07-31T00:00:00Z'),END=Date.parse('2026-09-10T00:00:00Z'),TH=.012,MAX=8;
type C={timestamp:number;open:number;high:number;low:number;close:number;volume:number}; const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(a:number[],p:number){const k=2/(p+1),r=[a[0]];for(let i=1;i<a.length;i++)r.push(a[i]*k+r[i-1]*(1-k));return r}
function atr(c:C[],p=14){const a:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const x=c[i],q=c[i-1];a.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return avg(a)}
function piv(c:C[],d:'LONG'|'SHORT'){const r:any[]=[];for(let i=2;i<c.length-2;i++){const v=d==='LONG'?c[i].low:c[i].high,w=c.slice(i-2,i+3).map(x=>d==='LONG'?x.low:x.high);if(d==='LONG'?v===Math.min(...w):v===Math.max(...w))r.push({index:i,price:v})}return r}
function tl(c:C[],d:'LONG'|'SHORT'){const a=piv(c,d).filter(x=>x.index>=Math.max(0,c.length-60)).slice(-5);if(a.length<2)return null;const b=a.at(-1),q=a.filter(x=>x.index>=b.index-72),x=q.at(-2),y=q.at(-1),dx=y.index-x.index,s=(y.price-x.price)/dx;if((d==='LONG'&&s<=0)||(d==='SHORT'&&s>=0))return null;const price=s*(c.length-1)+x.price-s*x.index,buf=Math.max(price*.005,atr(c)*.35);for(let i=y.index+1;i<c.length;i++){const line=s*i+(price-s*(c.length-1));if(d==='LONG'&&c[i].close<line-buf)return null;if(d==='SHORT'&&c[i].close>line+buf)return null}return{price,s}}
function st(c:C[]){const a=c.map(x=>x.close);if(a.length<32)return{k:50,d:50};const rs=(z:number[])=>{let g=0,l=0;for(let i=1;i<z.length;i++){const q=z[i]-z[i-1];if(q>0)g+=q;else l-=q}if(!l)return 100;return 100-100/(1+(g/l))};const r:number[]=[];for(let i=14;i<a.length;i++)r.push(rs(a.slice(i-14,i+1)));const raw:number[]=[];for(let i=13;i<r.length;i++){const w=r.slice(i-13,i+1),lo=Math.min(...w),hi=Math.max(...w);raw.push(hi===lo?50:(r[i]-lo)/(hi-lo)*100)}const k:number[]=[];for(let i=2;i<raw.length;i++)k.push(avg(raw.slice(i-2,i+1)));return{k:k.at(-1)!,d:avg(k.slice(-3))}}
function dc(c:C[],d:'LONG'|'SHORT',m:number){const a=c.map(x=>x.close),f=ema(a,5),s=ema(a,13),cross=d==='LONG'?f.at(-2)!<=s.at(-2)!&&f.at(-1)!>s.at(-1)!:f.at(-2)!>=s.at(-2)!&&f.at(-1)!<s.at(-1)!,z=st(c),turn=d==='LONG'?z.k>z.d:z.k<z.d,ext=d==='LONG'?z.k<20:z.k>80,candle=d==='LONG'?c.at(-1)!.close>c.at(-1)!.open:c.at(-1)!.close<c.at(-1)!.open;return m===1?cross:m===2?cross||(candle&&turn):cross||(turn&&!ext)}
function run(c:C[],m:number){let arm:any=null,tr:any=null;const o:any={armed:0,expired:0,entries:0,trades:0,wins:0,losses:0,net:0,gp:0,gl:0,captures:[]};for(let i=40;i<c.length;i++){const h=c.slice(0,i+1),x=c[i];if(tr){const hit=tr.d==='LONG'?x.high>=tr.tp:x.low<=tr.tp,sl=tr.d==='LONG'?x.low<=tr.stop:x.high>=tr.stop;if(sl||hit){const pnl=hit?(tr.d==='LONG'?tr.tp-tr.e:tr.e-tr.tp):(tr.d==='LONG'?tr.stop-tr.e:tr.e-tr.stop);o.trades++;o.net+=pnl;if(pnl>=0){o.wins++;o.gp+=pnl}else{o.losses++;o.gl-=pnl}tr=null;continue}continue}if(!arm){const cs:any[]=[];for(const d of ['LONG','SHORT'] as const){const t=tl(h,d);if(t){const dist=Math.abs((x.close-t.price)/t.price);if(dist<TH)cs.push({d,dist,tl:t.price})}}if(cs.length){cs.sort((a,b)=>a.dist-b.dist);arm={...cs[0],bar:i};o.armed++}}if(arm){const age=i-arm.bar;if(age>MAX){o.expired++;arm=null}else if(dc(h,arm.d,m)){const e=x.close,base=arm.d==='LONG'?Math.min(...h.slice(-10).map(q=>q.low)):Math.max(...h.slice(-10).map(q=>q.high)),stop=arm.d==='LONG'?Math.max(Math.min(base,e*.992),e*.965):Math.min(Math.max(base,e*1.008),e*1.035),risk=Math.abs(e-stop);if(risk){o.entries++;o.captures.push({ts:new Date(x.timestamp).toISOString(),d:arm.d,e,tl:arm.tl,age});tr={d:arm.d,e,stop,tp:arm.d==='LONG'?e+risk*2:e-risk*2};arm=null}}}}if(tr){const x=c.at(-1),p=tr.d==='LONG'?x.close-tr.e:tr.e-x.close;o.trades++;o.net+=p;if(p>=0){o.wins++;o.gp+=p}else{o.losses++;o.gl-=p}}return o}
async function get(p:string){const u=`https://api.kraken.com/0/public/OHLC?pair=${P[p]}&interval=240&since=${Math.floor(START/1000)-30*86400}`,r=await fetch(u,{cache:'no-store'}),j=await r.json(),k=Object.keys(j.result||{}).find(x=>x!=='last');return(j.result?.[k]||[]).map((x:any)=>({timestamp:x[0]*1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[6]})).filter((x:C)=>x.timestamp>=START&&x.timestamp<=END)}
export async function GET(){const by:any={},sum:any={};for(const p of Object.keys(P)){const c=await get(p);by[p]={};for(const m of [1,2,3])by[p][m]=run(c,m)}for(const m of [1,2,3]){const a:any={armed:0,expired:0,entries:0,trades:0,wins:0,losses:0,net:0,gp:0,gl:0};for(const p of Object.keys(P)){for(const k of Object.keys(a))a[k]+=by[p][m][k]||0}sum[m]={...a,winRate:a.trades?100*a.wins/a.trades:0,profitFactor:a.gl?a.gp/a.gl:0}}return NextResponse.json({researchOnly:true,architecture:'TL anchor -> armed setup -> direction change -> Entry 1/2 (bidirectional; ADD untouched)',threshold:TH,maxBars:MAX,period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},variants:{1:'5/13 cross',2:'5/13 cross OR candle+stoch turn',3:'5/13 cross OR non-extreme stoch turn'},summary:sum,byPair:by})}
